### ISSUE TITLE
Add a report user feature

### ISSUE THREAD

**Issue by SKB231** [RocketChat/EmbeddedChat#102]
As an EmbedChat developer

**I need to**: Allow users to be able:

- [ ] Click the report button next to a chat.
- [ ] Add a description, stating the report reason
- [ ] Click a button to confirm.

**So That**: Users can report messages from the Embeded Chat window, instead of having to do it from the main Rocket.Chat host.

**Acceptance Criteria**

- [ ] Add a report button, when A user hovers over the chat message.
- [ ] Upon cliking the report button, a small pop-up would appear asking why they would like to report it. This contains: A report description, cancel, and send Report.
- [ ] Make an API call to send the user's report message to server.

**Proposed changes**
<img width="638" alt="Screen Shot 2023-01-23 at 4 02 53 PM" src="https://user-images.githubusercontent.com/80944218/214149571-04b658af-f87d-4fe5-a3d7-bae771b7188e.png">

**Comment by SKB231** [comment]
Hey @sidmohanty11, as a developer new to open source and wanting to learn the ropes, I would love to work on this issue. Please give me the assignment and I can start working on it.
Thank you!

**Comment by sidmohanty11** [comment]
@SKB231 Go ahead!
