### ISSUE TITLE
[TODO] Support all OAuth providers

### ISSUE THREAD

**Issue by sidmohanty11** [RocketChat/EmbeddedChat#103]
As an EmbedChat developer

**I need to**: Make sure that EmbeddedChat supports all OAuth providers

**So That**: There is no immediate limitations and everyone can access their RC instance without any data loss.

**Acceptance Criteria**

- [ ] Nextcloud OAuth
- [ ] Facebook OAuth
- [ ] Gitlab OAuth
- [ ] GitHub OAuth
- [ ] WordPress OAuth
- [x] Normal Input based sign-in (Username/Password) - highest priority

Docs: https://docs.rocket.chat/use-rocket.chat/rocket.chat-workspace-administration/settings/oauth

### **Sign in with Google should change with - "JOIN"**
![image](https://user-images.githubusercontent.com/73601258/214300910-3d73de38-a73f-48c0-8cce-7d1795f49946.png)

### **Join should open up a modal with all the providers the user has given in props**
![image](https://user-images.githubusercontent.com/73601258/214301961-4a812b3f-7526-487f-8229-0b21ef10f372.png)

For Implementation, refer this PR: #12

**Comment by VipinDevelops** [comment]
Hey @sidmohanty11  this feature sounds interesting can you tell a little bit more about it like how one can implement these various approaches and how it's gonna work I may wanna work on this issue this will help me learn a lot 
Thank you!

**Comment by SKB231** [comment]
Hey @sidmohanty11, I have some experience working with OAuth. Could I work on, or collaborate with @VipinDevelops to work on this issue?

**Comment by VipinDevelops** [comment]
Yeah That's a great Idea we both can work on this issue we can also discuss about how to implement it more effective way and i implemented TOTP in EC so i have understanding of how auth flow and other components work

**Comment by VipinDevelops** [comment]
Yeah That's a great Idea we both can work on this issue we can also discuss about how to implement it more effective way and i implemented TOTP in EC so i have understanding of how auth flow and other components work 

And this is a huge task which required knowledge of different auth system 

Count me in 😄👍

**Comment by sidmohanty11** [comment]
@VipinDevelops @SKB231 Sure, go ahead. These are super super important for EmbeddedChat

**Comment by sidmohanty11** [comment]
For any doubts/issues you can directly DM me at https://open.rocket.chat

**Comment by VipinDevelops** [comment]
Hey @sidmohanty11 I have some questions about the implementation we should use a generic modal for this like the TOTP or should we create a Login Form can you guide use about it please

**Comment by kunbeg** [comment]
hey @sidmohanty11 can I also work on this issue with @VipinDevelops and @SKB231 ?

**Comment by sidmohanty11** [comment]
Sure @kunbeg !

**Comment by sidmohanty11** [comment]
We are one down, hurray!

Thanks @VipinDevelops and @SKB231 !

**Comment by VipinDevelops** [comment]
😄sure there is more to come very soon

**Comment by kunbeg** [comment]
@VipinDevelops please let me know where I can help in login enhancements ?

**Comment by VipinDevelops** [comment]
> @VipinDevelops please let me know where I can help in login enhancements ?

Do you have any experience with auth systems mentioned?

**Comment by kunbeg** [comment]
yes, I have read the code now and understood how google oauth is implemented, so on what oauth from the above list I can work upon?

**Comment by kunGup** [comment]
@sidmohanty11 After dm with @VipinDevelops we have decided that I will be working on gitlab oauth system and @VipinDevelops has already started working on facebook, twitter and github oauth systems. Is that fine?

**Comment by VipinDevelops** [comment]
Hello everyone, I wanted to inform you that if you're planning to work on this issue (https://github.com/RocketChat/EmbeddedChat/issues/103), please note that we currently don't have API endpoints available for authentication other than Google, Facebook, and Twitter. Therefore, we can only implement these authentication methods, and even for these, we require app secrets and other confidential credentials. You can find more information on this topic here: https://developer.rocket.chat/reference/api/rest-api/endpoints/other-important-endpoints/authentication-endpoints. Until we find a suitable solution for this problem, we won't be able to work on implementing other authentication methods. Thank you.

**Comment by adarsh500** [comment]
Hey @sidmohanty11, I can help with this issue. I recently refactored OAuth for RC4Conferences (https://github.com/RocketChat/RC4Conferences/pull/96) where I added support for github OAuth. I was hoping I could help by adding github oauth here as well, please let me know if I can work on this

**Comment by sidmohanty11** [comment]
@adarsh500 Thank you so much for the interest! The implementation in RC4Conferences looks amazing with the use of `NextAuth`. However, we want the OAuths to be tightly coupled or in a sense identical with all the provided OAuths from RC (can be any custom OAuth too). @abhinavkrin has discovered a really neat way in which we can achieve this with the use of existing RC APIs only, so if you want you can catchup with him to learn more about the flow. [I think he posted this inside #idea-embeddedchat-2023 channel so you can take a look there too]

Cheers!

**Comment by coderboy-yash** [comment]
hey @sidmohanty11  I want to work on this issue if this issue is  still open
