### ISSUE TITLE
Search Message Feature

### ISSUE THREAD

**Issue by vishakha-aggarwal** [RocketChat/EmbeddedChat#110]
As an EmbedChat developer

I need to: Add an option to search the messages

So That: EmbeddedChat Users can search messages

Acceptance Criteria

- [ ] Add search message functionality which allows authenticated users to search the messages.

**Comment by vishakha-aggarwal** [comment]
@sidmohanty11 I would like to work on this, Please assign it to me.

**Comment by sidmohanty11** [comment]
@vishakha-aggarwal can you provide some details about the UI implementation?

**Comment by vishakha-aggarwal** [comment]
Hey @sidmohanty11 , I am planning to implement it like this! Would it be fine or should I do some changes?
<img src="https://user-images.githubusercontent.com/76397035/215327364-e068a531-9034-400d-8efc-c52ea69221da.png" height="500px" width="800px">

**Comment by sidmohanty11** [comment]
Yup sure, go ahead! Looks amazing
