### ISSUE TITLE
 Room Information Feature 

### ISSUE THREAD

**Issue by VipinDevelops** [RocketChat/EmbeddedChat#111]
As an EmbedChat developer,

I need to: Add a feature that displays room information

So That: Users can view and manage the details of their rooms more easily and efficiently.

Acceptance Criteria:

- [ ] Display room name, and Description 
![image](https://user-images.githubusercontent.com/99081689/215326755-35a45abe-e284-4ddb-b84c-95586516504e.png)

**Comment by VipinDevelops** [comment]
Hey @sidmohanty11  I would like to take on the task of implementing the Room Information Feature for EmbedChat. Please assign this issue to me so that I can get started.

If there is any additional information or clarification needed, please let me know. I'm looking forward to contributing.

**Comment by sidmohanty11** [comment]
@VipinDevelops can you provide some details about the UI implementation?

**Comment by VipinDevelops** [comment]
> @VipinDevelops can you provide some details about the UI implementation?

I suggest maintaining a similar design to Rocket Chat by creating an attractive component using boxes and other elements. The resulting component can then be rendered on the message list.

**Comment by sidmohanty11** [comment]
@VipinDevelops can we use the Search component UI?

**Comment by VipinDevelops** [comment]
> @VipinDevelops can we use the Search component UI?

I was thinking the same i can reuse the code from search components
