### ISSUE TITLE
URL links are not appearing in Embedded Chat

### ISSUE THREAD

**Issue by SKB231** [RocketChat/EmbeddedChat#117]
### Description:
Embedded Chat is not displaying links after they are sent. As shown in the attached video, the links are visible in Rocket Chat, but not in Embedded Chat. This issue results in links being inaccessible to users.

### Steps to reproduce:

1. Paste a URL link in the input of Embedded Chat, either in plain text or in the format [<link name>](https://chat.openai.com/URL), and add text around the link if desired.
2. Send the input.

### Expected behavior:
- The link should be displayed in its entirety along with the raw text.

### Actual behavior:
- Everything except the link is displayed. 

In the video, I try to send the links in both formats, but after sending them, they are not visible in embeded chat, but only appear in the main RocketChat server and not in Embedded Chat.

https://user-images.githubusercontent.com/80944218/215970152-f30a668e-64e4-45c7-8613-1289920ebfc5.mov

**Comment by SKB231** [comment]
Hey @sidmohanty11, I would like to work on this issue, could you give me the assignment.
Thank you!

**Comment by sidmohanty11** [comment]
@SKB231 Thanks a lot for finding this out! We want this fixed badly.
