### ISSUE TITLE
Multiline Message not working

### ISSUE THREAD

**Issue by VipinDevelops** [RocketChat/EmbeddedChat#118]
### Description:
Users are unable to write multiline messages using the Control + Enter key combination. The program is not responding as expected and is sending the message instead of creating a new line.

### Steps to reproduce:
Open the messaging platform where the issue is present.
Type a message and press the Control + Enter keys to start a new line.

### Expected behavior:
The cursor should move to the next line and allow for the user to continue typing the message. The message should not be sent until the user chooses to do so.

### Actual behavior:
The message is sent as soon as the Control + Enter key combination is pressed, without allowing for a new line to be created. The user is unable to add additional lines to the message and must start over.

[Screencast from 2023-02-01 14-02-22.webm](https://user-images.githubusercontent.com/99081689/215992127-c0d6c436-1c27-442d-a9c2-27e1803e0868.webm)

**Comment by VipinDevelops** [comment]
Hey @sidmohanty11  have a look at this issue

**Comment by sidmohanty11** [comment]
Yup, please @VipinDevelops. Thanks!

**Comment by KoushikAD1234** [comment]
Hey @sidmohanty11 I want to work on this issue. Can you please assign it to me too...

**Comment by sidmohanty11** [comment]
Hey @KoushikAD1234 would you be willing to collaborate with @VipinDevelops for this? 

We would want `Ctrl + Enter` for windows and `Cmd + Enter` for mac to have a multiline input and send a multiline text.

**Comment by VipinDevelops** [comment]
> Hey @sidmohanty11 I want to work on this issue. Can you please assign it to me too...

Hey @KoushikAD1234  great to see you showing excitement on this issue but @SKB231 and I are already working on it he is helping me to understand the working of the front end and testing out the feature in Mac,  we will surely let you know if we face any issues 
Thank you!

**Comment by KoushikAD1234** [comment]
> Hey @KoushikAD1234 would you be willing to collaborate with @VipinDevelops for this?
> 
> We would want `Ctrl + Enter` for windows and `Cmd + Enter` for mac to have a multiline input and send a multiline text.

Yeah, I would like to collaborate with @VipinDevelops

**Comment by VipinDevelops** [comment]
Hey @sidmohanty11, @SKB231  and I had a discussion about this issue he had a better understanding of this issue  and he  also tested the feature on mac also please review his PR 
Thank you

**Comment by Pheewww** [comment]
hey, are you guys still working on it?

**Comment by VipinDevelops** [comment]
> hey, are you guys still working on it?
> 

This issue is fixed kanaki
