### ISSUE TITLE
Add a feature to mention EmbeddedChat users

### ISSUE THREAD

**Issue by KOMALDEWNANI** [RocketChat/EmbeddedChat#119]
As an EmbedChat developer

**I need to**:  Add a feature to mention EmbeddedChat users.

**So That**: communication and collaboration within the chat can be improved by directing the attention of a specific user to a message or comment.

**Acceptance Criteria**

- [ ] Display list of user[s]/all/everyone in the channel on typing "@".
       
![Screenshot (364)](https://user-images.githubusercontent.com/57641789/216127748-619b0854-92c9-49c1-9fb9-567106c50837.png)
 
- [ ] Highlight the mentioned user[s] in the chat.
     
![Screenshot (366)](https://user-images.githubusercontent.com/57641789/216128948-bd255ade-db84-4922-93e5-19ff3afd61ed.png)

**Comment by KOMALDEWNANI** [comment]
Hey @sidmohanty11, I would like to work on this issue. Please assign it to me. Thanks!

**Comment by sidmohanty11** [comment]
@KOMALDEWNANI yup this will be a great addition. Thanks!
