### ISSUE TITLE
Add more markdown styles

### ISSUE THREAD

**Issue by imf-ali** [RocketChat/EmbeddedChat#121]
As an EmbedChat developer

**I need to**: Have following markdown rules for HEADING, UNORDERED_LIST, ORDERED_LIST, TASKS, QUOTE, LINE_BREAK, Link, Color etc.

**So That**: All kinds of message are displayed in appropriate formatted way

**Acceptance Criteria**

- [ ] Heading
- [ ] Unordered list
- [ ] Ordered list
- [ ] Tasks
- [ ] Quote
- [ ] Reaction emoji
- [ ] Color
- [ ] Line Break

**Expected behaviour**
![image](https://user-images.githubusercontent.com/42451210/216824064-3fa98ae9-9f02-431e-a2ec-c829c8cc77cb.png)

**Actual behaviour**
![image](https://user-images.githubusercontent.com/42451210/216824091-fd5054c4-0505-4795-b843-bec671ed7190.png)

**Comment by imf-ali** [comment]
Hey @sidmohanty11 can you assign this issue to me

**Comment by VipinDevelops** [comment]
I think @SKB231  is already working on Links part you
