### ISSUE TITLE
UI and Code refactoring for release v0.0.3

### ISSUE THREAD

**Issue by sidmohanty11** [RocketChat/EmbeddedChat#132]
### UI
![image](https://user-images.githubusercontent.com/73601258/218664532-7d1887cc-a575-4d95-93b0-0803d4e6f361.png)

These are just my suggestions, if you have any amazing UI/UX idea please feel free to suggest it

### Code
- [x] Multiple API requests being made (refer #112) -> occurring at ChatBody.js while calling getMessagesAndRoles() twice
- [ ] Circular dependencies error from terminal `[0] (!) Circular dependencies
[0] src/components/Markup/elements/ItalicSpan.js -> src/components/Markup/elements/BoldSpan.js -> src/components/Markup/elements/ItalicSpan.js
[0] src/components/Markup/elements/BoldSpan.js -> src/components/Markup/elements/StrikeSpan.js -> src/components/Markup/elements/BoldSpan.js
[0] src/components/Markup/elements/ItalicSpan.js -> src/components/Markup/elements/BoldSpan.js -> src/components/Markup/elements/StrikeSpan.js -> src/components/Markup/elements/ItalicSpan.js`
- [ ] `src/components/auth` -> unnecessary Login.css, Login.module.css has improper casing - same with LoginForm, TwoFactorTotpModal.module.css
- [x] `src/components/Attachments/Attachment` has reference to hard-coded value to localhost - use RCInstance.getHost()
- [ ] `src/components/ChatHeader` - unused variables, do we need them?
- [x] `src/components/MessageList` -> `key` is missing
- [ ] `src/components/SearchMessage` unused variables
- [ ] `src/components/TotpModal` unused import
- [ ] Refactor three useEffects inside `src/index.js`
- [ ] Sometimes while development its giving a huge CSS loader error, does anybody know why?
- [ ] Ensure we use ESLint throughout the codebase and not disable rules (we can disable those which are not in our hands, for e.g, _id - dangling underscore) to get benefit of linting

**Comment by VipinDevelops** [comment]
Hi, could you please assign me the issue of Multiple API requests being made and the circular dependencies error mentioned in the terminal? Additionally, I noticed some other potential issues in the codebase such as unnecessary files, hard-coded values, unused variables and imports, and missing keys. I would be happy to work on those as well. Lastly, can we make sure to use ESLint throughout the codebase and avoid disabling rules, except for those outside of our control like dangling underscores 
 Thanks!

**Comment by VipinDevelops** [comment]
About the Task 5, I removed all the unused variables from the Chatheader component in this [PR](https://github.com/RocketChat/EmbeddedChat/pull/128/files)

**Comment by sidmohanty11** [comment]
@VipinDevelops sure! Please add your issues/findings here as a task list and let's go through them from here only so that we can ready ourselves for `0.0.3` launch.

And please keep PRs separate so that it will be easier for me to review. Thanks!

**Comment by VipinDevelops** [comment]
Yeah sure ill go through the code  deeply and will put new issues or any potential code convention I found 
Will try my best to organize the Pull request in a good manner so it will be easier for you to manage.

and yeah ill manage if any new contributors show interest in working on one of these issues and help them with that.

Thank you!

**Comment by sidmohanty11** [comment]
@VipinDevelops please keep them separate

**Comment by VipinDevelops** [comment]
> @VipinDevelops please keep them separate

Sure i will keep this in mind

**Comment by VipinDevelops** [comment]
I am starting with Task 1, I will check which API call is necessary and how can we store and reuse the information to avoid making other API call 

anyone who is interested in working on one of these issues feels free to share your approach here

**Comment by VipinDevelops** [comment]
> **@VipinDevelops** I will start with Task 4 and change hardcode localhost url from /src/context/RCInstance.js gethost().
> And for some UI changes I was thinking about adding a hover feature on buttons in chatInputFormattingToolbar to display info as follows:
> ![Screenshot from 2023-02-15 02-39-12](https://user-images.githubusercontent.com/92238941/218863623-fbde18e9-288f-42fa-9932-41a45349a7af.png)
> Or should i open new issue for it?

Sure go ahead make sure you make different PR for each fix

And take one issue at a time


Try to build UI like what sidharth suggested in UI changes , he want that all options hidden and a mechanism to show them if user wants to try to build something like that

No need to open another issue we can fix all issues  here 

Thank you

**Comment by CulturalProfessor** [comment]
Ok,thanks for heads up.

> > **@VipinDevelops** I will start with Task 4 and change hardcode localhost url from /src/context/RCInstance.js gethost().
> > And for some UI changes I was thinking about adding a hover feature on buttons in chatInputFormattingToolbar to display info as follows:
> > ![Screenshot from 2023-02-15 02-39-12](https://user-images.githubusercontent.com/92238941/218863623-fbde18e9-288f-42fa-9932-41a45349a7af.png)
> > Or should i open new issue for it?
> 
> Sure go ahead make sure you make different PR for each fix
> 
> And take one issue at a time
> 
> Try to build UI like what sidharth suggested in UI changes , he want that all options hidden and a mechanism to show them if user wants to try to build something like that
> 
> No need to open another issue we can fix all issues here
>
> Thank you

**Comment by CulturalProfessor** [comment]
> **@VipinDevelops** I will start with Task 4 and change hardcode localhost url from /src/context/RCInstance.js gethost(). And for some UI changes I was thinking about adding a hover feature on buttons in chatInputFormattingToolbar to display info as follows: ![Screenshot from 2023-02-15 02-39-12](https://user-images.githubusercontent.com/92238941/218863623-fbde18e9-288f-42fa-9932-41a45349a7af.png) Or should i open new issue for it?

@VipinDevelops hey regarding task 4:
![Screenshot from 2023-02-15 11-32-11](https://user-images.githubusercontent.com/92238941/218945760-b1023424-86b6-4d79-be49-bc90979dbd9a.png)
I changed url from localhost:3000 to host prop.

**Comment by VipinDevelops** [comment]
> > **@VipinDevelops** I will start with Task 4 and change hardcode localhost url from /src/context/RCInstance.js gethost(). And for some UI changes I was thinking about adding a hover feature on buttons in chatInputFormattingToolbar to display info as follows: ![Screenshot from 2023-02-15 02-39-12](https://user-images.githubusercontent.com/92238941/218863623-fbde18e9-288f-42fa-9932-41a45349a7af.png) Or should i open new issue for it?
> 
> @VipinDevelops hey regarding task 4:
> ![Screenshot from 2023-02-15 11-32-11](https://user-images.githubusercontent.com/92238941/218945760-b1023424-86b6-4d79-be49-bc90979dbd9a.png)
> I changed url from localhost:3000 to host prop.

We have a function "gethost" In you can find that in lib/api file use that function

**Comment by CulturalProfessor** [comment]
> We have a function this "gethost" you can find that in lib/api file use that function

![Screenshot from 2023-02-15 13-38-10](https://user-images.githubusercontent.com/92238941/218969297-d50c3fc2-64bc-4e87-910f-3bc9221e968a.png)
@VipinDevelops I have used RCInstance getHost().

**Comment by VipinDevelops** [comment]
> > We have a function this "gethost" you can find that in lib/api file use that function
> 
> ![Screenshot from 2023-02-15 13-38-10](https://user-images.githubusercontent.com/92238941/218969297-d50c3fc2-64bc-4e87-910f-3bc9221e968a.png) @VipinDevelops I have used RCInstance getHost().

No not like this don't make a new instance for this take a look at [this](https://github.com/RocketChat/EmbeddedChat/blob/main/src/components/MessageList/MessageList.js#L135)  and implement something like this

**Comment by VipinDevelops** [comment]
Yeah looks good to me you can make sure its working by console log the the host and i think you are good to make a PR

**Comment by KoushikAD1234** [comment]
![Screenshot (1)](https://user-images.githubusercontent.com/72178398/219042940-84ccac84-1273-4167-ad49-f56ff09e0162.png)
Hey @VipinDevelops I will start work on this avatar spacing.

![Screenshot (2)](https://user-images.githubusercontent.com/72178398/219043062-ebe9d73a-1a48-4f82-b777-ead83d17040f.png)
And this overflow one.

Do I need to raise an issue?

**Comment by VipinDevelops** [comment]
No you need to create another issue we will fix all these issue by making seperate PR's make sure you create different PR's for both issue

**Comment by CulturalProfessor** [comment]
@VipinDevelops @sidmohanty11  I have made a PR for task 4.

**Comment by CulturalProfessor** [comment]
@VipinDevelops regarding task-6 does MessageReactions component missing key in map ?
![Screenshot from 2023-02-16 12-15-34](https://user-images.githubusercontent.com/92238941/219288832-91e5e838-eb1e-4eda-a5b5-eb1bbb2afe0f.png)

**Comment by imf-ali** [comment]
> @VipinDevelops regarding task-6 is MessageReactions component missing key in map ? ![Screenshot from 2023-02-16 12-15-34](https://user-images.githubusercontent.com/92238941/219288832-91e5e838-eb1e-4eda-a5b5-eb1bbb2afe0f.png)

Just move the key attribute of Message component into Box component
<img width="535" alt="image" src="https://user-images.githubusercontent.com/42451210/219382526-d4721668-b08e-488b-93c3-364c3c930ecd.png">

**Comment by CulturalProfessor** [comment]
> Just move the key attribute of Message component into Box component <img alt="image" width="535" src="https://user-images.githubusercontent.com/42451210/219382526-d4721668-b08e-488b-93c3-364c3c930ecd.png">

![Screenshot from 2023-02-16 19-33-51](https://user-images.githubusercontent.com/92238941/219386458-95991f03-2267-47ab-b191-0f2903f48f98.png)
Ok right?

**Comment by imf-ali** [comment]
Yup, this should fix the key missing props

**Comment by KoushikAD1234** [comment]
Hey @VipinDevelops I have just made my first PR by fixing the weird avatar spacing and also changes the squared shape avatar box to rounded. Please Review once.

**Comment by VipinDevelops** [comment]
> Hey @VipinDevelops I have just made my first PR by fixing the weird avatar spacing and also changes the squared shape avatar box to rounded. Please Review once.

Changes look fine to me can you add a screenshot to your PR to show the changes you made 
Thank you

**Comment by CulturalProfessor** [comment]
Hey @sidmohanty11 regarding ui change of ChatInputFormattingToolbar can I replace it with a dropdown menu with options for formatting similar to menu in chat header to the left of ChatInput component?
![Screenshot from 2023-02-17 13-12-49](https://user-images.githubusercontent.com/92238941/219581757-4de4113b-3399-4350-8ad7-84a06acb9a9a.png)

**Comment by KoushikAD1234** [comment]
> > Hey @VipinDevelops I have just made my first PR by fixing the weird avatar spacing and also changes the squared shape avatar box to rounded. Please Review once.
> 
> Changes look fine to me can you add a screenshot to your PR to show the changes you made Thank you

![Screenshot from 2023-02-12 20-26-07](https://user-images.githubusercontent.com/72178398/219665752-7e981512-9b72-4d71-812e-6fa2ac39873f.png)
![Screenshot from 2023-02-16 13-17-00](https://user-images.githubusercontent.com/72178398/219665763-20ecbaac-c2d0-4408-929b-3a6c74599d34.png)
Changes that I have made in my very first PR. Please check it once @sidmohanty11

**Comment by honey-grapes** [comment]
Hi, has anyone started with the Task 7 or 8 yet? (src/components/SearchMessage unused variables, src/components/TotpModal unused import). If not maybe I can take a stab.

**Comment by CulturalProfessor** [comment]
> Hi, has anyone started with the Task 7 or 8 yet? (src/components/SearchMessage unused variables, src/components/TotpModal unused import). If not maybe I can take a stab.

I don't think anyone is on it.

**Comment by honey-grapes** [comment]
> > Hi, has anyone started with the Task 7 or 8 yet? (src/components/SearchMessage unused variables, src/components/TotpModal unused import). If not maybe I can take a stab.
> 
> I don't think anyone is on it.

Ok cool, let me try working on it!

**Comment by umangutkarsh** [comment]
Hi @sidmohanty11 , I've created a PR, please review it and let me know if any changes are required.
Hope you'll consider this. Thanks

**Comment by umangutkarsh** [comment]
@sidmohanty11 , what all tasks are pending in this issue? Can you confirm?

**Comment by WiseyXD** [comment]
@sidmohanty11 @VipinDevelops , what all tasks are pending in this issue? Can you confirm?

**Comment by arpitaneware06** [comment]
can you please give little bit description .

**Comment by sidmohanty11** [comment]
After GSoC, @abhinavkrin has made a lot of changes so I don't think this is still relevant. Closing this for now, if you feel like there are some minor issues remaining feel free to create an issue for it
