### ISSUE TITLE
Fix the positions of ChatHeader and Message Box

### ISSUE THREAD

**Issue by imf-ali** [RocketChat/EmbeddedChat#134]
### Description:
In the case of long messages, while scrolling down, the chat header becomes hidden, and while scrolling up message input box becomes hidden. Also we get two scroll bars, one for the message list component, other for complete window. Also there is scroll bar for going left and right in the window.

### Expected behavior:

- [ ] We should just have one scroll bar for scrolling the messages. 
- [ ] Chat header and message formatting box should be fixed.  
- [ ] There should be no scroll left to right or vice-versa.

### Actual behavior:
[screen-capture (1).webm](https://user-images.githubusercontent.com/42451210/219379676-54932336-5822-4cf8-a2b4-7cf6d43c0048.webm)

**Comment by KoushikAD1234** [comment]
Hey @sidmohanty11 I want to work on this issue. Please assign this to me.

**Comment by RahulNavneeth** [comment]
I have reviewed the issue and believe that I could make a valuable contribution to its resolution.
