### ISSUE TITLE
GoogleAuth - API not found (404)

### ISSUE THREAD

**Issue by RahulNavneeth** [RocketChat/EmbeddedChat#138]
### Description:

The backend API for GOOGLE-AUTH seem to be broken.

### Steps to reproduce:

1. Clone the repo
2. Fill the new .env with google-access-code
3. Try to login via google

### Expected behavior:

Getting Logged with Google account.

### Actual behavior:

'Something went wrong. Please check your TOTP and try again.' Error pops up since the response is undefined

<img width="371" alt="Screenshot 2023-02-17 at 9 03 08 PM" src="https://user-images.githubusercontent.com/50259284/219698455-d00013ec-1a56-4b9a-b9df-c7779d0b7a92.png">

**Comment by VipinDevelops** [comment]
Hey @RahulNavneeth This is not an issue

**Comment by RahulNavneeth** [comment]
@VipinDevelops

1. I had the project cloned
2. added my google access code to the .env file
3. npm install (both from playground and src)

That should potentially run the app right?

**Comment by VipinDevelops** [comment]
what do you mean by Google Access code have you followed the format given in `env[example]` file ?

**Comment by RahulNavneeth** [comment]
*Google Client ID

**Comment by VipinDevelops** [comment]
Have you setup correct redirect and callback URL in google Developer console ? 
and what values you put in  
REACT_APP_RC_HOST= 
REACT_APP_RC_ROOM_ID=

**Comment by RahulNavneeth** [comment]
Yeah I have added the callback url

this is how my .env looks like

**Comment by VipinDevelops** [comment]
> Yeah I have added the callback url
> 
> this is how my .env looks like
> `REACT_APP_RC_HOST='http://localhost:4000'`


It's wrong ❌ you should have the URL of your local RC server here

**Comment by RahulNavneeth** [comment]
Thanks for your time mate! Got it working 👍
