### ISSUE TITLE
Explore TOTP compatibility

### ISSUE THREAD

**Issue by sidmohanty11** [RocketChat/EmbeddedChat#14]
As an EmbedChat developer

**I need to**: Research upon TOTP

**So That**: EmbeddedChat works with TOTP enabled as well as disabled.

**Acceptance Criteria**

- [ ] Add TOTP capabilities!

**Comment by sidmohanty11** [comment]
Similar implementation in this PR -> https://github.com/RocketChat/RC4Community/pull/183

**Comment by VipinDevelops** [comment]
Hey can i try to implement this one I have very good understanding of auth system maybe I can fix this I might need some help to get this done

**Comment by sidmohanty11** [comment]
Sure @VipinDevelops !

**Comment by VipinDevelops** [comment]
@sidmohanty11  Kindly assign it to me so I'll Get started with this ASAP

**Comment by sidmohanty11** [comment]
@VipinDevelops go ahead

**Comment by VipinDevelops** [comment]
Thanks alot

**Comment by VipinDevelops** [comment]
hey @sidmohanty11 I have some questions about this issue can you explain in detail what is actually needed to be done if your asking to make embedded chat work with both TOTP enable and disabled 
[Screencast from 2022-12-27 16-29-36.webm](https://user-images.githubusercontent.com/99081689/209657228-2f91814a-fc77-4f2f-aa04-d516cc40c5c8.webm)
its working fine with both I can easily log in or logout embedded chat with TOTP enabled and disabled both

**Comment by sidmohanty11** [comment]
Enable TOTP-via-email
![Screenshot_20221230_210530](https://user-images.githubusercontent.com/73601258/210088909-aaa611e5-4c03-45b8-a51b-b24fc7f49813.png)

**Comment by VipinDevelops** [comment]
Hey @sidmohanty11 I have some questions about this issue you want me to just make it work with TOTP enable or disable or actually implement that TOTP feat in project and also it would be great if you can explain you expectation in detail so I can work according to that

**Comment by sidmohanty11** [comment]
@VipinDevelops hey! We want EmbeddedChat to work with TOTP enabled also.

We want a modal to appear to ask for TOTP code to the user incase TOTP is enabled in the RC server. I'm not sure about the implementation as I've not worked on it. You could definitely reach out to Dnouv and Pallanikanan if you have any questions and also try out how RC4Community handles it, it will give you an idea about the Auth part and also you'll get an understanding of another amazing project that you could contribute to!

Refer:
https://github.com/RocketChat/RC4Community/pull/183#issuecomment-1268004957

**Comment by VipinDevelops** [comment]
I understand the importance of adding TOTP support to EmbeddedChat, and I'm happy to help with the implementation. I'll definitely reach out to Dnouv and Pallanikanan for guidance and take a look at how RC4Community handles TOTP authentication.

**Comment by VipinDevelops** [comment]
Hey @sidmohanty11 I finished working with the logic of auth flow and implemented all the logic for login and logout and resend in a hook but I am finding it very difficult to implement a form/PopUp  for that where the user can input the TOTP

**Comment by sidmohanty11** [comment]
What problem are you facing? We could use the `Modal` [component](https://rocketchat.github.io/fuselage/fuselage/master/?path=/story/containers-modal--default) of fuselage with a number input field.

**Comment by VipinDevelops** [comment]
> What problem are you facing? We could use the `Modal` [component](https://rocketchat.github.io/fuselage/fuselage/master/?path=/story/containers-modal--default) of fuselage with a number input field.

Thanks for sharing this I will try to implete the form with this a soon make a PR a show you the changes.
