### ISSUE TITLE
Fix UI issues with current input bar

### ISSUE THREAD

**Issue by SKB231** [RocketChat/EmbeddedChat#144]
## Description:
This is an extension to the issue #132 to fix some of the issues related to the chat input bar:

### Can't scroll the text within the chat input.
1.  Paste a large amount of text to the input bar.
2. Try scrolling to the top of your input

### Chat box input does not automatically reduce size after user sends message.
1. When you have entered a large message, click enter.

### Full screen version has a scrollbar
1. Go to full screen mode.
2. Focus on chat input
3. Try scrolling

## Expected behavior:
- A) Should be able to scroll the text within the chat input
- B) Should automatically become resized to default chat window size.
- C) Nothing should happen.

### Actual behavior:
 - Currently can't scroll the text within the chat input.
 - Chat box input does not automatically reduce size after user sends message.
 - Full screen version has a scrollbar squashes or expands when we use this scroll bar.

The below displays all 3 issues in order.

https://user-images.githubusercontent.com/80944218/219932482-e9fde3ee-0b67-411a-9d8d-4e0bf788f95f.mp4

**Comment by SKB231** [comment]
Hi @sidmohanty11, could you give me the assignment to work on this issue?

**Comment by sidmohanty11** [comment]
@SKB231 Great findings! Please go ahead!
