### ISSUE TITLE
markdown shortcuts for bold and italic

### ISSUE THREAD

**Issue by VenomFate-619** [RocketChat/EmbeddedChat#147]
As an EmbeddedChat developer

**I need to**:
use the markdown shortcut to edit the text e.g:- Ctrl + B for bold , Ctrl + I for italic

**Acceptance Criteria**

- [ ] shortcut for bold
- [ ] shortcut for italic

**Comment by VenomFate-619** [comment]
@sidmohanty11 I like to fix this

**Comment by VenomFate-619** [comment]
@sidmohanty11

**Comment by VenomFate-619** [comment]
@sidmohanty11

**Comment by sidmohanty11** [comment]
@VenomFate-619 so sorry for late reply, please go ahead! For shortcuts please make it compatible with all OS. Thanks!

**Comment by satti-hari-krishna-reddy** [comment]
Hi @VenomFate-619 are you still working on this issue ?

**Comment by Yashraj7890** [comment]
Hi @sidmohanty11 , is this issue still open?
I would love to work on this can it be assigned to me if this issue is still open?

**Comment by sidmohanty11** [comment]
Go ahead!

**Comment by Yashraj7890** [comment]
Just needed some clarification.

Here we are aiming at implementing markdown shortcuts for the user such that when the user wants to change the font type of the text message he's going to send.

I hope I'm right here.

**Comment by sidmohanty11** [comment]
@Yashraj7890 Yes yes, for example, if I select any word and do Ctrl+B, it should bold it in markdown syntax. 

cc @abhinavkrin

**Comment by abhinavkrin** [comment]
Hey, @Yashraj7890 I think you should target replicating how it is handled currently by the existing action buttons (bold, italic). 
To explain, when a user presses `CTRL+B` the selected text should be wrapped with *. For example `hello there` -> `*hello there*`. And if no text is selected add ** to the position of the cursor and set the cursor position in the middle of the two * characters. This should be the ideal solution. You can share if you have any other approach.

**Comment by Yashraj7890** [comment]
Noted👍, I'm on it.

**Comment by Yashraj7890** [comment]
Hey @abhinavkrin 

I have made a pull request which successfully implements the feature with the exact behavior you have decribed.

**Comment by abhinavkrin** [comment]
Thanks, @Yashraj7890 I have merged the changes.
