### ISSUE TITLE
Wrong dimensions for larger sizes in Emojis

### ISSUE THREAD

**Issue by RahulNavneeth** [RocketChat/EmbeddedChat#154]
### Description:

Wrong dimensions for larger sizes in Emojis

### Steps to reproduce:

1. Clone the repo
2. Launch the application
3. Use only emojis when communicating via the chat function.

### Expected behavior:

<img width="447" alt="Screenshot 2023-02-24 at 5 36 46 PM" src="https://user-images.githubusercontent.com/50259284/221176071-673fbfa0-77a7-412b-b759-a1dd99d0739b.png">

### Actual behavior:

<img width="447" alt="Screenshot 2023-02-24 at 5 36 09 PM" src="https://user-images.githubusercontent.com/50259284/221176125-897fb899-8fd2-4414-92e9-95c36ccb8d01.png">

**Comment by Ananya2001-an** [comment]
Hey @RahulNavneeth I am actually trying to set up my google client ID to run the app but it's not working. Can you help out?

**Comment by RahulNavneeth** [comment]
Hello @Ananya2001-an ,

Please follow the steps outlined below:

After initiating the RC core on the host 3000, navigate to 'http://localhost:3000/admin/settings/OAuth'.
Locate the Google option, enable 'GoogleLogin', and provide the required inputs (SECRET_ID and CLIENT_ID).
(For the EmbeddedChat project):
3. CD into the playground directory.

Duplicate the .env[example] file and rename it to ".env".
`REACT_APP_RC_HOST='http://localhost:3000'
 REACT_APP_RC_ROOM_ID="GENERAL"
 REACT_APP_GOOGLE_CLIENT_ID="YOUR_GOOGLE_CLIENT_ID"`
 
This should complete the process.

Also please ensure to add the redirect URL in your Google console for the provided OAuth credentials.

Best regards.

**Comment by Ananya2001-an** [comment]
> Hello @Ananya2001-an ,
> 
> Please follow the steps outlined below:
> 
> 1. After initiating the RC core on the host 3000, navigate to 'http://localhost:3000/admin/settings/OAuth'.
> 2. Locate the Google option, enable 'GoogleLogin', and provide the required inputs (SECRET_ID and CLIENT_ID).
> 
> (In EmbeddedChat project):
> 3. CD into the playground directory.
> 
> Duplicate the .env[example] file and rename it to ".env".
> `REACT_APP_RC_HOST='http://localhost:3000'
>  REACT_APP_RC_ROOM_ID="GENERAL"
>  REACT_APP_GOOGLE_CLIENT_ID="YOUR_GOOGLE_CLIENT_ID"`
>  
> This should complete the process.
> 
> Also please ensure to add the redirect URL in your Google console for the provided OAuth credentials.
> 
> Best regards.

Thanks for the detailed explanation @RahulNavneeth I will try it on my end. 😊

**Comment by Ananya2001-an** [comment]
Also the RC core means the main Rocket.Chat repo right? Actually I faced issues running it since I am trying to use gitpod. Do you have any clue as to how to set it up on gitpod?

**Comment by SANGAAM** [comment]
I am not able to Login i think there is an issue in Google authentication

**Comment by SANGAAM** [comment]
![Screenshot (8)](https://user-images.githubusercontent.com/96041004/221350343-74ed4f52-5efc-45ac-9c91-776e014e6516.png)
and what i have found even after REACT_APP_RC_HOST='http://localhost:3000'
my project is opening in 4000

**Comment by SANGAAM** [comment]
![Screenshot (9)](https://user-images.githubusercontent.com/96041004/221350452-984b5c0d-f71c-4685-aa72-50570c52189c.png)
and my project is opening in localhost 4000 even after setting REACT_APP_RC_HOST='http://localhost:3000'

**Comment by VipinDevelops** [comment]
> ![Screenshot (9)](https://user-images.githubusercontent.com/96041004/221350452-984b5c0d-f71c-4685-aa72-50570c52189c.png) and my project is opening in localhost 4000 even after setting REACT_APP_RC_HOST='http://localhost:3000'

Can you please share browser error logs?

**Comment by RahulNavneeth** [comment]
> ![Screenshot (9)](https://user-images.githubusercontent.com/96041004/221350452-984b5c0d-f71c-4685-aa72-50570c52189c.png) and my project is opening in localhost 4000 even after setting REACT_APP_RC_HOST='http://localhost:3000'

I see your EmbeddedChat is hosted at port 3000

To be clear
1. EmbeddedChat should be hosted in port 4000
2. RC core at port 3000

In .env

REACT_APP_RC_HOST='http://localhost:3000/' -> This calls the RC core app

**Comment by RahulNavneeth** [comment]
Hey @sidmohanty11 , Can you kindly review this pull request. Thanks 😄

**Comment by RahulNavneeth** [comment]
> Also the RC core means the main Rocket.Chat repo right? Actually I faced issues running it since I am trying to use gitpod. Do you have any clue as to how to set it up on gitpod?

If you can tell me what error you are experiencing, I might be able to assist you even though I am not familiar with setting up the project on localhost using Gitpod.

**Comment by SANGAAM** [comment]
Well I have hosted that in 4000 still that doesn't work
And what u mean by RC core is this the Rocket. Chat repository u r talking about??

**Comment by RahulNavneeth** [comment]
> Well I have hosted that in 4000 still that doesn't work
> 
> And what u mean by RC core is this the Rocket. Chat repository u r talking about?? 
> 
> 

Yup, Rocket.Chat is the core repo - only if you get the Core app hosted in port 3000 you would able to continue

**Comment by RahulNavneeth** [comment]
> > Well I have hosted that in 4000 still that doesn't work
> > 
> > And what u mean by RC core is this the Rocket. Chat repository u r talking about?? 
> > 
> > 
> 
> Yup, Rocket.Chat is the core repo - only if you get the Core app hosted in port 3000 you would able to continue 

Note : Both EmbeddedChat and RC Core should be hosted simultaneously.

EmbeddedChat on 3000
RC Core on 4000

**Comment by SANGAAM** [comment]
https://www.linkedin.com/in/sangam-chaudhary-4b5047226
Hey this is my linkedin account if u get any time then pls share the video on how u setup the project it will great help for me
I will try from side too
And thnx btw

**Comment by RahulNavneeth** [comment]
Sure mate! Will do 👍
