### ISSUE TITLE
Section for tagging the user is not closing 

### ISSUE THREAD

**Issue by VenomFate-619** [RocketChat/EmbeddedChat#163]
### Description:
The section that is there for tagging the user is not closing despite removing the @ symbol also.
If I close and open the Embedded Chat, it is still there.

it mostly happens when the message box is empty,
and sometime when there is text in it.

### Steps to reproduce:

1. type @ in the empty message box
2. clear the @ 

### Actual behavior:

https://user-images.githubusercontent.com/67755128/222218450-c9ed5b0d-53aa-4850-8292-ecd0b5b87e83.mp4

**Comment by VenomFate-619** [comment]
It consists of two task
- handling when textarea is empty
- handling when @ is typed after the text without the space (in this case there should be no suggestion) 
![image](https://user-images.githubusercontent.com/67755128/222223707-650b968d-5f2e-47bf-a68e-1c3ee5bca7d0.png)
no suggestion

![image](https://user-images.githubusercontent.com/67755128/222223831-667ea9d0-b3aa-4d0e-a708-2765838dbe3d.png)
suggestion

**Comment by VenomFate-619** [comment]
@sidmohanty11 i like to fix this.

**Comment by sidmohanty11** [comment]
Thanks @VenomFate-619 for picking this up!

**Comment by raazseth** [comment]
Is this still open? If yes then please assign me this issue @sidmohanty11
