### ISSUE TITLE
Focus is not transferred to new message after sending

### ISSUE THREAD

**Issue by CulturalProfessor** [RocketChat/EmbeddedChat#166]
### Description:

After sending a new message the focus is not automatically transferred to new message by scrolling.
### Steps to reproduce:

1.  Go to chatinput.
2. Type a new message
3. Press send.

### Expected behavior:

[Screencast from 02-03-23 07:09:12 PM IST.webm](https://user-images.githubusercontent.com/92238941/222446465-def70bba-52d2-4b6f-9c03-e01f5b484e46.webm)

### Actual behavior:

[Screencast from 02-03-23 07:13:48 PM IST.webm](https://user-images.githubusercontent.com/92238941/222446497-18dbeabe-0360-4aef-b4fe-90fcfb7105ae.webm)

**Comment by CulturalProfessor** [comment]
Hey @sidmohanty11 can I work on this issue?

**Comment by MahirPatel3130** [comment]
Yeah i can also work on this issue!

**Comment by sidmohanty11** [comment]
@CulturalProfessor Sure, please go ahead! This will be a huge thing for us to shift focus on the most recent message without user constantly shifting their scrollview.

**Comment by sidmohanty11** [comment]
@MahirPatel3130 Sure, please catchup with @CulturalProfessor and check if collaboration is possible for this

**Comment by raazseth** [comment]
Please assign me this issue, I can fix it @sidmohanty11

**Comment by sidmohanty11** [comment]
@raazseth yup sure go ahead!

**Comment by imrahulkanna** [comment]
Is the bug resolved? If not, I can help out!

**Comment by umangutkarsh** [comment]
Hey @sidmohanty11 . If no one is working on it, can I take it up?

**Comment by umangutkarsh** [comment]
Hey @sidmohanty11 . Can you please take out your time and review the PR #370 . 
Also please let me know if anything is required,

Thanks
