### ISSUE TITLE
Better Responsiveness across screens of different sizes

### ISSUE THREAD

**Issue by RonLek** [RocketChat/EmbeddedChat#2]
As an EmbedChat developer
**I Need to:** Make the EmbedChat component Responsive
**So That:** It fits best on screens of all sizes and gives users usage options based on screen size

**Acceptance Criteria**
- Emoji picker responsiveness.
- Defaults
  - width = 100%
  - height = 1/4 of the screen size
- Full-screen button on top right to expand the component to occupy the entire screen.
  - Show/hide features based on current size of the component.

**Comment by sidmohanty11** [comment]
- show message box for smaller screen
- create an emojipicker similar to RC-mobile
- fullscreen height on maximize
![image](https://user-images.githubusercontent.com/73601258/175044113-a27c7bdd-cd6a-4d80-a7ae-2271181030c8.png)
