### ISSUE TITLE
Contributor Widget Not Updating

### ISSUE THREAD

**Issue by samad-yar-khan** [RocketChat/EmbeddedChat#208]
### Steps to reproduce:

1. Go to the GitHub ReadMe.
2. The contributor widget is not being updated.

### Expected behavior:

1. The Contributor Widget should be updated in the GitHub ReadMe with updated PR count every day.

### Actual behavior:

1. Although the contributor widget itself is updating and an updated widget is being sent to GitHub by our CDN. The GitHub caching mechanism has cached the current widget as the max-age was not served in the [CacheControl](https://www.imperva.com/learn/performance/cache-control/#:~:text=Cache%2DControl%3A%20Max%2DAge,-The%20max%2Dage&text=After%20expiring%2C%20a%20browser%20must,to%20request%20a%20newer%20version.) Headers .

**Comment by MahirPatel3130** [comment]
can i fix this @sidmohanty11
