### ISSUE TITLE
Remove fuselage menu component from header

### ISSUE THREAD

**Issue by abhinavkrin** [RocketChat/EmbeddedChat#235]
Replace the fuselage's Menu component in the header with our own custom component.
The component should implement our theming system.

**Comment by Ciggzy1312** [comment]
@abhinavkrin I would like to give this one a try

**Comment by abhinavkrin** [comment]
Hey @Ciggzy1312 Thank you! I have assigned this issue to you.

**Comment by KushalSr** [comment]
Hi @abhinavkrin Do we've to build  the Menue componenet from scratch?
