### ISSUE TITLE
Replace @rocket.chat/fuselage-toastbar with custom toastbar

### ISSUE THREAD

**Issue by abhinavkrin** [RocketChat/EmbeddedChat#236]
Replace @rocket.chat/fuselage-toastbar with our own custom toastbar.
Any other alert solution could be discussed.
The component should implement our theming system.

**Comment by anjy7** [comment]
Hey @abhinavkrin, I would like to work on this issue..

**Comment by abhinavkrin** [comment]
Thanks @anjy7 I have assigned this issue to you.

**Comment by adityamishra3** [comment]
Hey @abhinavkrin , I would like to work on this issue, can you make me another assignee as well.
Thanks
