### ISSUE TITLE
Replace fuselage's MessageEmoji component with our own component

### ISSUE THREAD

**Issue by abhinavkrin** [RocketChat/EmbeddedChat#238]
1. Replace the fuselage's MessageEmoji component with our own component
2. The component should implement our theming system

**Comment by abhinavkrin** [comment]
hey @mdozairq, thanks for stepping up. I have assigned it to you.

**Comment by abhinavkrin** [comment]
Hey @mdozairq If you look into `packages/react/src/components/Markdown/Markdown.js` You can see that there is MessageEmoji being used. We need to get rid of this import from @rocketchat/fuselage. 
You can either change the code in the Markdown component itself or create a new MessageEmoji component. The thing is we need to preserve the current functionality and get rid of the @rocketchat/fuselage.
Please do take care that theming is being taken care of while doing this task.

**Comment by KushalSr** [comment]
Hey Can I work on this issue ?

**Comment by umangutkarsh** [comment]
Hey @abhinavkrin , if this issue is not resolved, please it to me, I'm working on this.
