### ISSUE TITLE
Replace the fuselage's Checkbox component with our own component

### ISSUE THREAD

**Issue by abhinavkrin** [RocketChat/EmbeddedChat#239]
1. Replace the fuselage's Checkbox component with our own component
2. The component should implement our theming system
3. There needs to be a prop to disable interactivity.

**Comment by FidalMathew** [comment]
@abhinavkrin  I'd like to work on this issue.

**Comment by abhinavkrin** [comment]
Hey @FidalMathew  Thank you. I have assigned this issue to you.

**Comment by FidalMathew** [comment]
@abhinavkrin could you guide me on how I should approach this issue?

**Comment by abhinavkrin** [comment]
Hey, The CheckBox component should render a simple check element. You could render <input type="check" /> keeping our theming guidelines in mind. https://github.com/RocketChat/EmbeddedChat/blob/develop/packages/react/docs/theming.md

**Comment by KushalSr** [comment]
Hello Can I work for this isssue?

**Comment by KushalSr** [comment]
@abhinavkrin Hi I like to work on this issue
