### ISSUE TITLE
Replace fuselage's Avatar with our Avatar component in RoomInformation

### ISSUE THREAD

**Issue by abhinavkrin** [RocketChat/EmbeddedChat#240]
We have already built our own Avatar Component. It needs to be replaced with the fuselage's Avatar component used in the RoomInformation component.
This could be a good first issue for new contributors.

**Comment by coderboy-yash** [comment]
hey I am interested in this issue can you please assign this issue to me.

**Comment by abhinavkrin** [comment]
Hey @coderboy-yash You can start working one this issue and create a PR for the same.

**Comment by KushalSr** [comment]
Hey is this issue is still open. Can I work on this issue?
