### ISSUE TITLE
Disproportionate Emoji Size in Reaction Count Button

### ISSUE THREAD

**Issue by abhinavkrin** [RocketChat/EmbeddedChat#266]
### Description:
The emoji used in the reaction count button appears significantly larger than the accompanying count number, resulting in a visual inconsistency.

### Steps to reproduce:
1. React to a message if the message does not have any reaction yet.

### Expected behavior:
![screenshot_expected](https://github.com/RocketChat/EmbeddedChat/assets/15830206/38044a35-5fe2-4fbd-82e5-24b70f259f69)

### Actual behavior:
![reaction-emoji-toobig](https://github.com/RocketChat/EmbeddedChat/assets/15830206/53ce2c08-1bfc-4f9b-bf60-002da2dbf4b8)

**Comment by wrth1337** [comment]
I would like to work on this issue @abhinavkrin

**Comment by abhinavkrin** [comment]
Hey @wrth1337 Thank you! I have assigned it you.

**Comment by wrth1337** [comment]
I have a fix but it uses the deleted Markdown.css from #262 .
At this point, you should first get the "Markdown.styles.js" file running.

**Comment by Jenil-Dobariya** [comment]
Hi @abhinavkrin , I want to know if this issue is fixed or not. I can give a try to resolve this if not already.

**Comment by noothiakshith** [comment]
Hi @abhinavkrin , i have started working on this issue as, this is first contribution if it is not assigned ,kindly assign to me . I can make my effort to fix this incase if not already

**Comment by Rohit-Sharmaa** [comment]
@noothiakshith are you working on this issue ??

**Comment by abhinavkrin** [comment]
Hey @Rohit-Sharmaa could you fix this. I will be happy to merge your fix.

**Comment by Shubham071122** [comment]
Hey @abhinavkrin are you working on this issue, if not can you assign me i give a try.

**Comment by tj8016** [comment]
when i am trying to solve this issue so i set up this project locally I follow all the instruction all command are running fine but on `packages/api` when i run `yarn dev` terminal giving error

<img width="895" alt="Screenshot 2023-11-13 at 11 30 51 PM" src="https://github.com/RocketChat/EmbeddedChat/assets/80402614/0fe0dd45-54ef-4ec2-9e59-862ac1986c2f">

<img width="1440" alt="Screenshot 2023-11-13 at 11 29 59 PM" src="https://github.com/RocketChat/EmbeddedChat/assets/80402614/77569cc8-be6e-4e75-8160-3466282bbfa8">

How can i deal with this issue ?

**Comment by abhinavkrin** [comment]
Hey @tj8016 You need to first run `yarn` in the EmbeddedChat directory which will install and build the required packages.

**Comment by tj8016** [comment]
> To solve this issue, I set up this project locally I follow all the instruction, All command are running fine but on `packages/api` when i run `yarn dev` terminal giving me error `Usage Error: Couldn't find a script named "parcel".`
> 
> <img alt="Screenshot 2023-11-13 at 11 30 51 PM" width="895" src="https://user-images.githubusercontent.com/80402614/282548705-0fe0dd45-54ef-4ec2-9e59-862ac1986c2f.png"> <img alt="Screenshot 2023-11-13 at 11 29 59 PM" width="1440" src="https://user-images.githubusercontent.com/80402614/282548757-77569cc8-be6e-4e75-8160-3466282bbfa8.png">
> How can i deal with this issue ?

I run `yarn` on `EmbeddedChat directory` but not work.
actually the problem, on `package.json` there are no `parcel` `devDependencies`
I install it then and it is working.

**Comment by tj8016** [comment]
> Hey @tj8016 You need to first run `yarn` in the EmbeddedChat directory which will install and build the required packages.

I run yarn in the EmbeddedChat directory but did not worked.
After checking the `package.json` of packeges/api directory i found the parcel devDependencies not install, I install it and it is working now.

**Comment by tj8016** [comment]
I want to work in this issue
