### ISSUE TITLE
Implement Star Icon in message header for Starred Messages

### ISSUE THREAD

**Issue by abhinavkrin** [RocketChat/EmbeddedChat#267]
Messages that are starred currently do not have a distinct visual representation. We need to implement a star icon next to starred messages for clear differentiation. The message data received from the server already has the flag if the message is starred or not.

**Expected Behaviour**
![star](https://github.com/RocketChat/EmbeddedChat/assets/15830206/94c5e1b8-2e0d-471e-9ab9-998b71ffb067)

**Comment by anjy7** [comment]
I would like to take this one @abhinavkrin

**Comment by abhinavkrin** [comment]
Hey @anjy7 Thank you! I have assigned this issue to you.
