### ISSUE TITLE
Styling of Members List is Broken Due to Removal of Fuselage Styles

### ISSUE THREAD

**Issue by abhinavkrin** [RocketChat/EmbeddedChat#268]
### Description:
With the move from fuselage components to our custom components, the styling of the members list has been affected, causing visual inconsistencies.

### Expected behavior:
![expected](https://github.com/RocketChat/EmbeddedChat/assets/15830206/d73c56eb-1b0c-4aa3-8160-964ab80a02ea)
We don't need the user's online status for now. and it can be ignored.

### Actual behavior:
![members](https://github.com/RocketChat/EmbeddedChat/assets/15830206/f06d1f3d-ccb7-4bd8-8505-8fad71d88bf2)

**Comment by abhinavkrin** [comment]
Hey @Yashraj7890, Thank you! I have assigned it you.

**Comment by Yashraj7890** [comment]
It's going to be my first PR 😁, I'm on it.

**Comment by abhinavkrin** [comment]
Hey @Yashraj7890, 
You can click on the three dots in the header and then click on the members option.

**Comment by Yashraj7890** [comment]
Sir, the actual problem I'm facing is that, when I'm clicking on the members button the API calls are blocked by CORS (according to the console) and thus I'm unable to add any members.

**Comment by abhinavkrin** [comment]
Hey, you will have to enable CORs in the RocketChat settings.

**Comment by Yashraj7890** [comment]
Thank you it made it work, I'm back at it.

**Comment by Yashraj7890** [comment]
A component named "Option" has been imported from fuselage to design the RoomMemberItem component, I've decided to create another custom component to fix the broken structure, should I begin to code on this approach?

**Comment by abhinavkrin** [comment]
Closing this as fixed by #282
