### ISSUE TITLE
Misalignment of 'JOIN' Button

### ISSUE THREAD

**Issue by abhinavkrin** [RocketChat/EmbeddedChat#269]
### Description:
The 'JOIN' button is not properly aligned (vertically) with the rest of the elements in the chat interface.
![join-button-not-aligned](https://github.com/RocketChat/EmbeddedChat/assets/15830206/11447cc6-ced0-4659-b2cc-3fe18ede0666)

### Steps to reproduce:
You need to be logged out to see join buttton

**Comment by Kamlesh72** [comment]
May I work on this issue @abhinavkrin ?

**Comment by tanu-chahal** [comment]
@abhinavkrin In Menu>Search the Enter button is also vertically misaligned, can we add that too in this issue? Or need a new one for that.

![search-enter-button-misalignment](https://github.com/RocketChat/EmbeddedChat/assets/117712672/ee4a2d39-bc78-4609-a64c-f2bad287ca5b)


@Kamlesh72 have you started working on this?

**Comment by abhinavkrin** [comment]
Hey @tanu-chahal  Thank you for finding it out. You can create issues for any bug that you encounter.

**Comment by abhinavkrin** [comment]
Hey @Kamlesh72  Thank you! I have assigned it to you.
