### ISSUE TITLE
Wrong text alignment in connection with emojis

### ISSUE THREAD

**Issue by wrth1337** [RocketChat/EmbeddedChat#273]
### Description:

The text of a message is vertically misarranged as soon as an emoji appears in the text message.

### Steps to reproduce:

1. Write a text message with an emoji inside the message.
2. The text appears at the bottom of the message-body.

### Expected behavior:

![Expected](https://github.com/RocketChat/EmbeddedChat/assets/135323978/8c5b930b-8310-43b8-8574-7293328ee727)

### Actual behavior:

![Actual](https://github.com/RocketChat/EmbeddedChat/assets/135323978/5320d5f5-3ba3-4d66-9c21-ae989cb2dae5)

**Comment by wrth1337** [comment]
Hey @abhinavkrin. I'd like to work on that issue. Already got a solution to this.

**Comment by abhinavkrin** [comment]
Hey @wrth1337 thank you for pointing this out. I will go and assign it to you.
