### ISSUE TITLE
Improve DefaultTheme.js @mui/system

### ISSUE THREAD

**Issue by Akshat111111** [RocketChat/EmbeddedChat#275]
As an EmbeddedChat developer

**I need to**:
Implementing the  thing using mui/system create theme function.

**So That**:
 It will be more compatible with material UI.

**Acceptance Criteria**

- [ ] TODO 1
- [ ] TODO 2
- [ ] TODO 3

**Comment by abhinavkrin** [comment]
Hey @Akshat111111 , we don't use material UI for EmbeddedChat. So this change is not required for the project.
