### ISSUE TITLE
Style the scrollbar for message list.

### ISSUE THREAD

**Issue by abhinavkrin** [RocketChat/EmbeddedChat#284]
The default scrollbar in the message list panel currently maintains the browser's default style. It is functional but doesn't align with the application's overall aesthetic. Implementing a custom style for the scrollbar will enhance the visual appeal and user experience, making the UI more consistent and engaging.

###### Expected Scrolbar Design
![Expected Scrollbar design](https://github.com/RocketChat/EmbeddedChat/assets/15830206/3fab3a95-fcff-4f1b-b41d-453f4964e89a)

**Comment by umangutkarsh** [comment]
Hey @abhinavkrin . I can work on this. Please assign this issue to me. Thanks.
Also if you are free I needed some help with the testing of the changes in _Search Message_ feature.

**Comment by Pr-anjali** [comment]
Hey @abhinavkrin I am new to open source and would like to work on it. Please assign this issue to me.

**Comment by abhinavkrin** [comment]
Great to see the enthusiasm! This issue won't be assigned to one person—everyone is welcome to submit a PR. I'll review all contributions. Thanks for your input!

**Comment by Yashraj7890** [comment]
Noted 👍
