### ISSUE TITLE
Unexpected appearance of the message options box

### ISSUE THREAD

**Issue by Yashraj7890** [RocketChat/EmbeddedChat#296]
### Description:

No similar issue has been raised previously.

The message options box which appears while hovering over a particular message is appearing in undesirable places.

![Screenshot (16)](https://github.com/RocketChat/EmbeddedChat/assets/98230836/50aced65-c7b3-4cde-91c2-6236877a217e)

![Screenshot (17)](https://github.com/RocketChat/EmbeddedChat/assets/98230836/81d9743d-de74-4601-b15a-c800410d17c6)

### Steps to reproduce:

1. Click on the 3 dots on the top right corner to open a list and when the list appears hover over any message.
2. The box which appears will appear over the list.
3. You may open member list or any kind of box which appears over the message list and then hover over any message.
4. This video may provide a clear explanation:
5. 👇

https://github.com/RocketChat/EmbeddedChat/assets/98230836/afa6f5a3-2799-44e6-a492-3ab2c191a259

### Expected behavior:

The Rocket Chat desktop app handles it in the following way:

https://github.com/RocketChat/EmbeddedChat/assets/98230836/4f4fb74f-efff-4b8c-be8c-bafe7a3ba984

The box appears under the list.

I'm willing to submit a pull request.

**Comment by abhinavkrin** [comment]
Hey @Yashraj7890 Thanks a lot for raising this issue. I am eagerly waiting for your fix 🤞🚀

**Comment by Yashraj7890** [comment]
I'm on it👍
