### ISSUE TITLE
Providing real-time chat functionality using RocketChat node.js SDK.

### ISSUE THREAD

**Issue by RonLek** [RocketChat/EmbeddedChat#3]
As an EmbedChat developer
**I Need to:** use Rocket.Chat Node.Js SDK
**So That:** real-time chat functionality can be achieved with my component and the RC server

**Acceptance Criteria**
- [ ] Install Node.js SDK
- [ ] Initialize an RC Instance and connect to RC Server.
- [ ] Create websockets on RC server.

**Comment by sidmohanty11** [comment]
# Tech debt

- warning of using `eval`
- a discrepancy of markdown between RC and EmbeddedChat
