### ISSUE TITLE
Implement tooltips

### ISSUE THREAD

**Issue by Yashraj7890** [RocketChat/EmbeddedChat#307]
The RocketChat desktop has these nice and clean pop ups which appear while hovering over a particular element and also provide info about the element.

The video below may provide a clearer description:

https://github.com/RocketChat/EmbeddedChat/assets/98230836/099fe217-c799-4803-a79d-554e33e9a2ed

I would love to implement these kinds of pop-ups for the suitable elements in the embedded chat component.

**Comment by abhinavkrin** [comment]
Hey @Yashraj7890 , that would be nice to add. It will also help users know about the action the button performs. Could you share what approach you would take to implement it.

**Comment by Yashraj7890** [comment]
I think designing a separate tooltip component and then applying the component to the required elements and making the component to trigger only while hovering over the elements would do the job.

**Comment by abhinavkrin** [comment]
@Yashraj7890  That would be a nice solution. We could create a popover component that would wrap its children. Whenever the component is hovered the popover should be displayed.
It would be even nicer if we could detect long press on mobiles to display the popover.

**Comment by Yashraj7890** [comment]
Yeah for sure,we could try to do that too.

**Comment by Yashraj7890** [comment]
So @abhinavkrin should I go ahead with it or would you like to add something else to it?

**Comment by abhinavkrin** [comment]
Yes. You can create a pr for this. You can keep the name Tooltip or as you like it.

**Comment by Yashraj7890** [comment]
Hey @abhinavkrin , after going through a good amount of research I've figured out that there are various kind of ways to implement tooltips and implementing tooltips from scratch requires handling of many UI based corner cases, an example is displayed in the screenshot below.

![Screenshot (31)](https://github.com/RocketChat/EmbeddedChat/assets/98230836/e11eea1c-eb97-4e79-ba8f-a3ce3ab1e4de)

and there exist many such cases, although they can be handled, I think using prebuilt tooltips provided by libraries like material UI etc will make it easier for us to implement them and as they are flawless (designed for production use) it will also make the 
injection of tooltips for further components really easy.

I would like you to share your thoughts on this and please let me know in which way you want to direct this.

**Comment by Yashraj7890** [comment]
Hey @abhinavkrin after a bit of research and going through the types of UI-based corner cases I might face while implementing tooltips,
(an example) :

![Screenshot (31)](https://github.com/RocketChat/EmbeddedChat/assets/98230836/d090421a-2b45-4901-96f9-1132a163b794)

 I have decided to go and use tooltips provided by MUI, which also makes it easier for us to inject tooltips for any other component which may be introduced afterwards. 

A corresponding PR has been raised by me.
