### ISSUE TITLE
App crashed when message is sent in threads

### ISSUE THREAD

**Issue by umangutkarsh** [RocketChat/EmbeddedChat#328]
### Description:

The app is crashing when a message is sent in threads. The message is sent but right after it is sent, the app crashes.

### Steps to reproduce:

1. Move the cursor to any message.
2. Select `Reply in threads option`
3. Send a message. 
4. The app crashes but the message is sent,

### Expected behavior:

The App should should not crash when the message is sent,

### Actual behavior:
![thr](https://github.com/RocketChat/EmbeddedChat/assets/95426993/9d7d8f01-e43d-495a-92cf-14906869be56)

**Comment by abhinavkrin** [comment]
Hey @umangutkarsh I already fixed this issue today. Could you pull and confirm if its working?

**Comment by umangutkarsh** [comment]
> Hey @umangutkarsh I already fixed this issue today. Could you pull and confirm if its working?

Ok. I just saw your comment. Will check

**Comment by umangutkarsh** [comment]
> Hey @umangutkarsh I already fixed this issue today. Could you pull and confirm if its working?

Yes working.

**Comment by abhinavkrin** [comment]
Great! Thank you for noticing it. Glad it is fixed. 
Closing as fixed by #327
