### ISSUE TITLE
Room Information not displayed

### ISSUE THREAD

**Issue by umangutkarsh** [RocketChat/EmbeddedChat#340]
### Description:

Room Information not displayed when Room-Information menu option is clicked.

### Steps to reproduce:

1. Click on three dot menu.
2. Click on Room - Information
3. Information not displayed.

### Expected behavior:
Room Information should be displayed.

### Actual behavior:
<img width="649" alt="roomInfo" src="https://github.com/RocketChat/EmbeddedChat/assets/95426993/1902b61e-2731-4063-8f63-fe89628840b3">

**Comment by umangutkarsh** [comment]
Maintainers, Please let me know if this is a bug or correct me if I am wrong.

**Comment by saurabhbakolia** [comment]
I would like to work on this issue!

**Comment by devanshkansagra** [comment]
Can you tell me what you have added in the room information??

**Comment by sidmohanty11** [comment]
Definitely an issue, please feel free to take this up!

**Comment by ameeetgaikwad** [comment]
Getting started on this issue.

**Comment by ameeetgaikwad** [comment]
@sidmohanty11 Can you tell what information should be present under "Room Information" ?
