### ISSUE TITLE
Thread Messages not deleted when the Main message is deleted

### ISSUE THREAD

**Issue by umangutkarsh** [RocketChat/EmbeddedChat#343]
### Description: 

The thread messages of a message are not deleted (like they are deleted in Rocket.Chat) when the message is deleted.

### Steps to reproduce:

1. Type some message in input
2. Click on threads icon in menu of a message.
3. Write some messages in threads
4. Delete the main message. The thread messages still remain.

### Expected behavior:
All the messages of threads should be deleted like they are deleted when the main message is deleted in Rocket.Chat app.

### Actual behavior:
[threads.webm](https://github.com/RocketChat/EmbeddedChat/assets/95426993/2a241d54-60d4-4170-bfb3-d39ce8e4cbcb)

**Comment by umangutkarsh** [comment]
Maintainers, @abhinavkrin . Please confirm if this issue should be left as it is, or it should be worked upon like this is there on the Rocket.Chat app.

**Comment by umangutkarsh** [comment]
Hey @abhinavkrin . Should I work on this one?

**Comment by abhinavkrin** [comment]
Hey @umangutkarsh 
The thread messages arent deleted when the main message is deleted. 
![image](https://github.com/RocketChat/EmbeddedChat/assets/15830206/d819cf10-8c6d-48e8-8a6f-52b302e44eeb)

**Comment by umangutkarsh** [comment]
Okay, thread messages are getting delete for me. 


[delt.webm](https://github.com/RocketChat/EmbeddedChat/assets/95426993/d721d5e1-7a96-486f-9ff2-0f255d887b0c)
