### ISSUE TITLE
Support for thread messages

### ISSUE THREAD

**Issue by sidmohanty11** [RocketChat/EmbeddedChat#35]
As an EmbedChat developer

**I need to**: Create the functionality to view and write in threads

**So That**: Users can use the thread functionality of RC and messages don't get cluttered in EmbeddedChat

**Acceptance Criteria**

- [ ] UI for threads
- [ ] List all thread messages of a thread
- [ ] Writing a message inside that thread should trigger sendMessage to that specific thread

**Comment by vishakha-aggarwal** [comment]
Hey, I woud like to work on this issue. Can you please assign it to me?

**Comment by sidmohanty11** [comment]
Sure @vishakha-aggarwal ! This will be a huge contribution! Threads are one of the most important and powerful feature of Rocket.Chat

**Comment by nawed2611** [comment]
Hey @vishakha-aggarwal, are you still working on this?

**Comment by vishakha-aggarwal** [comment]
Hey @nawed2611 , I am still working on it. If I wouldn't able to resolve the issue, I will definitely let you know.

**Comment by nawed2611** [comment]
If there's any blocker, maybe I can help

**Comment by vishakha-aggarwal** [comment]
Sure, I will let you know if I would face any issue, right now I am almost done, just left with styling.

**Comment by imf-ali** [comment]
hey @vishakha-aggarwal whats the update on this, are you still working on this or facing any difficulty?

**Comment by vishakha-aggarwal** [comment]
Hey @imf-ali , There is a blocker in the implementation of threads, issue #112  this need to be resolved first as we can't afford to call API unnecessarily again and again.

**Comment by abhinavkrin** [comment]
Hey @sidmohanty11, We have recently switched to using realtime API. Since this issue is active for a long time. The old ways that have been developed (but not merged) might not work. I have created a PR to integrate it using the realtime feature.
https://github.com/RocketChat/EmbeddedChat/pull/183
