### ISSUE TITLE
Error when rendering LazyLoad

### ISSUE THREAD

**Issue by umangutkarsh** [RocketChat/EmbeddedChat#353]
### Description:

Some error is occurring when the lazy-load is rendered in storybook.

### Steps to reproduce:

1. Do `yarn storybook` and storybook will open.
2. Click on `LazyLoad component -> Simple`
3. See the error

### Expected behavior:

It should be rendered without any errors.

### Actual behavior:

![err](https://github.com/RocketChat/EmbeddedChat/assets/95426993/d92d1edd-bc57-4c89-8c62-8e94c20bf08e)

### Expected Solution:
Remove the `EmbeddedChatLazy.stories.js`, since not used .

**Comment by abhinavkrin** [comment]
Hey, @umangutkarsh We no longer have the component used in this story. We can delete this story.

**Comment by umangutkarsh** [comment]
OK sure.

**Comment by umangutkarsh** [comment]
Hey @abhinavkrin . Will this pr work?
