### ISSUE TITLE
Typing-Text issue

### ISSUE THREAD

**Issue by umangutkarsh** [RocketChat/EmbeddedChat#365]
### Description:
The Typing text which is displayed when the user is typing, is being displayed even when the message is sent and no user is typing. It only disappears when clicked out of the text area. 

### Steps to reproduce:

1. Open storybook
2. Click on `ChatInput` text-area.
3. Type a message. And Send it.
4. The `<user> is typing...` message still appears until clicked outside somewhere.

### Expected behavior:

The typing message should not be displayed when message is sent. Only displayed when user is typing.

### Actual behavior:
[type.webm](https://github.com/RocketChat/EmbeddedChat/assets/95426993/9e330bf9-7d14-4108-b6b8-178b176f082b)

**Update**: The Issue was only when 'Enter' key is pressed, not when message is sent through the Send Button in text area.

**Comment by tanmaymokal2002** [comment]
Hey, I want to try this. but this is my first issue i don't know where to find code felp...or this storybook to open locally on my laptop. Plss helpp..

**Comment by umangutkarsh** [comment]
Working on this one.
