### ISSUE TITLE
Image and Video attachments not rendering on chat.

### ISSUE THREAD

**Issue by umangutkarsh** [RocketChat/EmbeddedChat#368]
### Description:

The Image and videos which are sent on chat are not rendered like they should.

### Steps to reproduce:

1. Click on Attach-More-Plus-Icon to attach files in Chat-input.
2. Select any image or video, and send the message.
3. These are not rendered on chat

### Expected behavior:

Should be rendered.

### Actual behavior:
[attach.webm](https://github.com/RocketChat/EmbeddedChat/assets/95426993/cce4a31b-ede8-4dee-baac-805699e32ea3)

**Comment by Akshun-01** [comment]
Hey, I would like to work on this one!

**Comment by ameeetgaikwad** [comment]
@umangutkarsh off topic here. Not able to set up local environment.
![image](https://github.com/RocketChat/EmbeddedChat/assets/76063569/bfc49cc4-582e-458e-b26e-14511af5dbe6)
Not able to send message?

I've rocket.chat server running on localhost:3000. Is it necessary to run `yarn dev` in the `packages/auth` as well? For the `packages/react` to work?

**Comment by umangutkarsh** [comment]
> @umangutkarsh off topic here. Not able to set up local environment. ![image](https://private-user-images.githubusercontent.com/76063569/293492114-bfc49cc4-582e-458e-b26e-14511af5dbe6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQwMzg1MTMsIm5iZiI6MTcwNDAzODIxMywicGF0aCI6Ii83NjA2MzU2OS8yOTM0OTIxMTQtYmZjNDljYzQtNTgyZS00NThlLWIyNmUtMTQ1MTFhZjVkYmU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjMxVDE1NTY1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFjNGYyZmE5M2E4NGRjNDBjN2E2MTk0OWJlYmUyNTgxNTBkMzdkZGRmYTMwMzk4ZWU2YWQ0N2NkYmFlN2EwY2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jm9EwV6bbz9fpaAukzn9G-fxbDXvoHESLFH9OlG16rI) Not able to send message?
> 
> I've rocket.chat server running on localhost:3000. Is it necessary to run `yarn dev` in the `packages/auth` as well? For the `packages/react` to work?

Click on JOIN, Just login using the credentials with which you have signed up.

**Comment by Yashraj7890** [comment]
@umangutkarsh I think this issue is fixed or the images weren't rendering because of some network issue that you might be facing.

https://github.com/RocketChat/EmbeddedChat/assets/98230836/068a7c5b-b833-448f-ba2e-c819b1797dcc

**Comment by Kamlesh72** [comment]
> @umangutkarsh off topic here. Not able to set up local environment. ![image](https://private-user-images.githubusercontent.com/76063569/293492114-bfc49cc4-582e-458e-b26e-14511af5dbe6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQxMjI3MTMsIm5iZiI6MTcwNDEyMjQxMywicGF0aCI6Ii83NjA2MzU2OS8yOTM0OTIxMTQtYmZjNDljYzQtNTgyZS00NThlLWIyNmUtMTQ1MTFhZjVkYmU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAxVDE1MjAxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNhN2JkZDY4ZWNmNmM3ZTkwMzUzNDk1YjE4MzhiODRkYTZiZThhYzkzYzIzZDcwODA0OWM0ZmVkNzhiNDk1NjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.InZy1jMkAFC9yRdyWYj2cbVWs0neyhBrLDTud2Qx25M) Not able to send message?
> 
> I've rocket.chat server running on localhost:3000. Is it necessary to run `yarn dev` in the `packages/auth` as well? For the `packages/react` to work?

No, it is not necessary.
Send the console logs.

**Comment by ameeetgaikwad** [comment]
> > @umangutkarsh off topic here. Not able to set up local environment. ![image](https://private-user-images.githubusercontent.com/76063569/293492114-bfc49cc4-582e-458e-b26e-14511af5dbe6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQwMzg1MTMsIm5iZiI6MTcwNDAzODIxMywicGF0aCI6Ii83NjA2MzU2OS8yOTM0OTIxMTQtYmZjNDljYzQtNTgyZS00NThlLWIyNmUtMTQ1MTFhZjVkYmU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjMxVDE1NTY1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFjNGYyZmE5M2E4NGRjNDBjN2E2MTk0OWJlYmUyNTgxNTBkMzdkZGRmYTMwMzk4ZWU2YWQ0N2NkYmFlN2EwY2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jm9EwV6bbz9fpaAukzn9G-fxbDXvoHESLFH9OlG16rI) Not able to send message?
> > I've rocket.chat server running on localhost:3000. Is it necessary to run `yarn dev` in the `packages/auth` as well? For the `packages/react` to work?
> 
> Click on JOIN, Just login using the credentials with which you have signed up. Are you able to send and receive messages?

NO, I did clicked the join button and entered the email/username and password nothing happens further.

**Comment by Akshun-01** [comment]
Hey @ameeetgaikwad, 
- go to localhost:3000/admin (rocketChat server)
- go to settings
- search for CORS 
- then scroll down to find `enable cors` option
- toggle it ON and save changes
- now try to login again

 See if this works! ^^

**Comment by umangutkarsh** [comment]
> @umangutkarsh I think this issue is fixed or the images weren't rendering because of some network issue that you might be facing.
> 
>  20240101203504.mp4

Hi @Yashraj7890 . 
I'll check this out again. Thanks for letting me know.

**Comment by umangutkarsh** [comment]
> @umangutkarsh I think this issue is fixed or the images weren't rendering because of some network issue that you might be facing.
> 
>  20240101203504.mp4

Hi @Yashraj7890 
The images are not rendering on my chat screen. Will close it if anyone else confirms.

**Comment by Akshun-01** [comment]
Hey @umangutkarsh, earlier it was working fine for me (2nd January) 

#### But today I am also facing the same problem 
![image](https://github.com/RocketChat/EmbeddedChat/assets/93793691/cc6cd782-27c7-4b66-be7a-a9d9b7c4f75e)

**Comment by Akshun-01** [comment]
And Now its working again :)

![image](https://github.com/RocketChat/EmbeddedChat/assets/93793691/a8be37d4-ddc1-4dd8-b039-cb75f740ec98)

**Comment by umangutkarsh** [comment]
Hey @Akshun-01 . Thanks for letting me know, maybe because of some network problem. 
**Closing this issue, since problem occurred due to network issue**
I'll close this issue.
