### ISSUE TITLE
Proper Error Handling for "Message Too Long" 

### ISSUE THREAD

**Issue by Akshun-01** [RocketChat/EmbeddedChat#384]
### Description:
In Embedded Chats, if the message is too long then it gives an error message of 
`Error sending message, log in again.`
and logs the user out. 

Getting logged out for sending long texts is a not very likely user experience, this should be properly handled with an Error message ( similar to what is done on RocketChat).

### Steps to reproduce:

1. Try to send a very long text or code.

### Expected behavior:
![image](https://github.com/RocketChat/EmbeddedChat/assets/93793691/5c484138-1b35-47ac-a94e-39c09df73700)

### Actual behavior:
[Screencast from 01-02-2024 05:52:29 PM.webm](https://github.com/RocketChat/EmbeddedChat/assets/93793691/ac764715-09d6-45db-a8b0-ec37ffb6e9ec)

**Comment by Akshun-01** [comment]
@abhinavkrin @sidmohanty11 
Please confirm if this issue needs attention. I would love to start working on this.

**Comment by rahat2134** [comment]
yup! I also want to work on this issue.

**Comment by Akshun-01** [comment]
Hey @sidmohanty11 @abhinavkrin,
I have completed the modal and error handling. I am currently writing the code to change `message to file` and send it as an attachment. It is a bit tricky. So I just wanted to confirm before moving forward with this issue. 
Is this issue approved?

- Also here is the current status of the issue (I will be improving the UI during the final PR)
[Screencast from 01-10-2024 05:15:30 AM.webm](https://github.com/RocketChat/EmbeddedChat/assets/93793691/1f8775b2-836a-41b4-aab2-8576a489a2d5)

Will raise a draft soon! ^^

**Comment by Akshun-01** [comment]
### Update :
Hey, I have added the `convert to file` logic as well. Here is the current status.

https://github.com/RocketChat/EmbeddedChat/assets/93793691/1473487f-4f12-43d2-81d1-bc08805417b3

Some bugs need attention, I will try to fix them soon and send a PR (or should I send a draft pr, so you can also see the code changes ?)

[Any suggestions or feedback would be appreciated] @sidmohanty11

**Comment by Spiral-Memory** [comment]
Great find, @Akshun-01 , and great work fixing this as well.

**Comment by Akshun-01** [comment]
Hello @abhinavkrin @sidmohanty11,
resolved all the linting and conflicting issues. The changes are ready for review. 
Do take a look in your free time thanks! ✨
