### ISSUE TITLE
Height of the chatbox is more when we run the project

### ISSUE THREAD

**Issue by devanshkansagra** [RocketChat/EmbeddedChat#410]
### Description:

When we run the command yarn storybook in ```packages/react``` the height of ```ChatInput``` is more

### Expected behavior:

![image](https://github.com/RocketChat/EmbeddedChat/assets/125076549/e52a71cd-9ace-4cac-b960-97719ade3975)

### Actual behavior:

![image](https://github.com/RocketChat/EmbeddedChat/assets/125076549/e90d9f20-11a7-43a0-bc3c-aa372caeb77c)

When we click on ```height```: ```set string``` button in ```Addons``` it comes down

### The behaviour:
![image](https://github.com/RocketChat/EmbeddedChat/assets/125076549/5dc18fdd-2416-4d42-85e8-245c10fa0222)

**Comment by Akshun-01** [comment]
Hey @devanshkansagra. I think it is meant for the settings panel.
To view it properly, click on the `expand` (desktop icon) to view it in full-screen mode.

**Comment by Spiral-Memory** [comment]
@devanshkansagra, I agree with @Akshun-01. This doesn't seem to be a bug; I believe it's meant to function this way.

**Comment by devanshkansagra** [comment]
Ok then no issue, I will close this issue
