### ISSUE TITLE
Can't Login without enabling CORS in RocketChat Server

### ISSUE THREAD

**Issue by Akshun-01** [RocketChat/EmbeddedChat#432]
### No Response if CORS is not enabled

When I am trying to setup the project for development, I cant login without enabling the CORS setting in the main RocketChat server. 
Also it is not giving any error for it, and I couldn't know what the error was.

- Now I asked some other members as well, not all are facing this issue. So i really don't know what the core cause is, but it would be good to look into it.

### Steps to reproduce:
1. Start RocketChat server locally
2. start Embedded Chats server locally
3. Try to login

### Expected behavior:
This case should be documented in the setting up locally part. 
Also, some kind of error mentioning this would be helpful.

### Actual behavior:
No Response and no documentation for this sort of scenario.

**Comment by Spiral-Memory** [comment]
@Akshun-01 , I believe it is enforced by the browser when attempting to request an API from a different domain. This needs to be addressed on the backend by allowing Access Origin headers, and enabling CORS on rocket chat server does the same. Additionally, the information regarding this matter is covered in a video available on the page: https://github.com/RocketChat/EmbeddedChat/wiki/FAQs.

However, displaying it as an error during setup as a notification is not very useful, as it is a general browser-enforced security measure that is logged in the console. Perhaps the steps can be included in the documentation on how to deploy the app, although they are already discussed in the video.

**Comment by Akshun-01** [comment]
Ohh, ok ok.
Yeah, I also only wanted some insights on this one. Because not everyone was facing this issue. So adding a little hint about it in the documentation is more than enough. 
Because the first time I faced this, I had no clue how to proceed.

Thanks Zishan! ^^
