### ISSUE TITLE
Toggle feature not working for chat input formatting toolbars

### ISSUE THREAD

**Issue by shivang-16** [RocketChat/EmbeddedChat#434]
### Description
The toggle feature is not working as expected, and the formatting is not applied or removed accordingly for chat input formatting toolbars

### Steps to Reproduce
In the Chat input box .. just click on bold, itatlic, strike, code, multiline button

### Expected Behavior
Formatting option(bold, itatlic, strike, code, multiline) toggles the formatting on/off for the selected text. For example, if I click on bold, the selected text should become bold. If I click on bold again, the bold formatting should be removed.

### Actual Behavior
The formatting toggle feature does not work as expected. Clicking on the formatting option just apply the formatting for the selected text.

### Additional Information
- Browser/Environment: Chrome 121
- Operating System: macOs
- Device: Pc

https://github.com/RocketChat/EmbeddedChat/assets/125182653/5e062f06-5589-446e-aa7c-8e7dc6edff24

**Comment by Ujjwal-123M** [comment]
HI @abhinavkrin can you assigned this issue to me?

**Comment by Ujjwal-123M** [comment]
HI @abhinavkrin  please assign this issue to me.

**Comment by shivang-16** [comment]
> HI @abhinavkrin  please assign this issue to me.

Hi @Ujjwal-123M , I've already raised the pr for this issue
