### ISSUE TITLE
[Feat]: Adding a section to view all the threads going in the channel

### ISSUE THREAD

**Issue by Spiral-Memory** [RocketChat/EmbeddedChat#441]
As an EmbeddedChat developer, 

**I need to**:
Add a section where all threads can be seen in one place.

**So That**:
Users can easily navigate through the ongoing threads in the channel.

**Acceptance Criteria:**

- [ ] Identify the modal where these threads should be displayed.
- [ ] Design the modal in a manner consistent with the existing layout of the Rocket.Chat main application.
- [ ] Retrieve thread information using the REST API and present it in the modal. Each thread should be clickable, allowing users to navigate directly to the respective thread.

For reference, please find the video of the original Rocket.Chat application, which inspired this idea:

https://github.com/RocketChat/EmbeddedChat/assets/78961432/03e9f58a-427b-4008-b290-0335bd6277f1

**Comment by Spiral-Memory** [comment]
@abhinavkrin, @sidmohanty11, I have started working on this issue. In the meantime, please let me know if you also believe that this feature should be implemented in the EmbeddedChat as well.

**Comment by abhinavkrin** [comment]
Yes @Spiral-Memory Thar would be great. It was already in our ToDo list.

**Comment by Spiral-Memory** [comment]
Sure, Thank you for your confirmation.

**Comment by Spiral-Memory** [comment]
@abhinavkrin @sidmohanty11 , I have added the thread menu feature and created a pull request. Kindly go through it to check if everything is good or if any changes are required.
