### ISSUE TITLE
Unexpected behavior of the typing users feature.

### ISSUE THREAD

**Issue by Yashraj7890** [RocketChat/EmbeddedChat#443]
### Description:

When the user types he is able to see the notification that he is currently typing but the code has already filtered out the current username from the typing users list so that the user can only be notified when someone other than him types.

### Expected behavior:

User should be only notified when someone else is typing instead of when he himself is.

### Actual behavior:
![Screenshot (61)](https://github.com/RocketChat/EmbeddedChat/assets/98230836/b2352dd8-f854-4cf2-b0fa-d5580a8ac85c)

**Comment by umangutkarsh** [comment]
Hi @Yashraj7890 . Thanks for raising this issue. 
But this issue was already raised in issue #372

**Comment by Yashraj7890** [comment]
Oh that's on me😅, I'll takedown the PR and the issue . Thanks for your help😁
