### ISSUE TITLE
Implement UIKit Modal Support in EmbeddedChat

### ISSUE THREAD

**Issue by abhinavkrin** [RocketChat/EmbeddedChat#474]
To further enhance user interaction and engagement within this embedded environment, there's a need to integrate UIKit modals. UIKit modals are interactive dialogs that can display a wide range of content, including forms, information, confirmations, and more, directly within the chat interface.

#### Objective:
The primary goal is to implement UIKit Modal support in EmbeddedChat. This implementation should ensure that UIKit modals render correctly within the chat environment and that user actions on these modals are processed accurately. This feature is crucial for enabling a more interactive and engaging user experience, as it allows for complex interactions to be handled directly within the chat interface.

#### Key Requirements:
1. **UIKit Modal Rendering**: Enable the rendering of UIKit modals within EmbeddedChat.
2. **Action Processing**: Ensure that any actions taken within a UIKit modal (e.g., button clicks, form submissions) are correctly captured and communicated back to the Rocket.Chat server for processing. This may involve API calls or other mechanisms to handle user interactions.

**Comment by Spiral-Memory** [comment]
Sure @abhinavkrin, I would like to work on it. Currently i am not very sure about what it does but will surely understand and do it with your help.

**Comment by abhinavkrin** [comment]
@Spiral-Memory Check how these are implemented in mobile app, livechat, rocket.chat

**Comment by Spiral-Memory** [comment]
Sure.

**Comment by Sayan4444** [comment]
@Spiral-Memory https://developer.rocket.chat/apps-engine/extend-app-capabilities/apps-engine-user-interface/contextual-bar
This is what is meant by modal i guess

**Comment by Spiral-Memory** [comment]
Yes, for instance, running a slash command might initiate a process on the RC server, and it should display some UI. The outcome could be directly shown in the EC after processing on the RC.

**Comment by Sayan4444** [comment]
Yes, exactly like the notion app
