### ISSUE TITLE
Align invitation sidebar UI with RocketChat

### ISSUE THREAD

**Issue by JeffreytheCoder** [RocketChat/EmbeddedChat#482]
As an EmbeddedChat developer

**I need to**:
Align the UI of Invite Members sidebar with what we have in RocketChat

**So That**:
Users can have a better and consistent UX with member invitation. Currently, 
- Invite link is long and often cut off, making it hard to copy
- Spacing and color are not consistent with those in RocketChat
- The back button is on the top right, which is not consistent with other UIs
<img width="300" alt="Screenshot 2024-02-27 at 9 19 04 AM" src="https://github.com/RocketChat/EmbeddedChat/assets/35394596/dd02d546-0179-4228-bc5d-07c045ab941f">

The objective is to make the invitation sidebar looks and behaves similar to what we have in RocketChat:
<img width="611" alt="Screenshot 2024-02-27 at 9 21 29 AM" src="https://github.com/RocketChat/EmbeddedChat/assets/35394596/3d52a222-5773-44c6-8fe5-a30109c499d2">
Not sure if the Edit Invite feature is necessary in EmbeddedChat. Not included for now, but we can raise another issue.

**Acceptance Criteria**
- [x] Add a copy button besides the invite link
- [x] Make spacing and color consistent with those in RocketChat
- [x] Move back button to the top left

**Comment by JeffreytheCoder** [comment]
Working on this

**Comment by sidmohanty11** [comment]
Cool!
