### ISSUE TITLE
Feat: Add a 'Files' menu option view the files shared in the channel

### ISSUE THREAD

**Issue by umangutkarsh** [RocketChat/EmbeddedChat#485]
As an EmbeddedChat developer

**I need to**: Implement a sidebar menu option

**So That**:  Where users can view all the Files shared in the channel just like in like in Rocket.Chat.

**Acceptance Criteria**

- [x] Create a menu option, and a sidebar tab to view all shared 'Files'
- [x] Use the REST API endpoint to fetch all the files of that channel,
- [x] Integrate it with the existing codebase.

**Screenshots**
![files](https://github.com/RocketChat/EmbeddedChat/assets/95426993/2113eb59-4692-4879-8516-f0c7a9f5a457)
<img width="959" alt="ec-files" src="https://github.com/RocketChat/EmbeddedChat/assets/95426993/eed075d6-8a79-4f6a-bd47-286c45a57f73">

**Comment by umangutkarsh** [comment]
Will create a PR shortly after I finish it.

If not required now, might be considered after releasing the stable version.
Thanks

**Comment by JeffreytheCoder** [comment]
@umangutkarsh You might want to take a look at this issue #490

**Comment by umangutkarsh** [comment]
> @umangutkarsh You might want to take a look at this issue #490 

@JeffreytheCoder the files are rendered properly on my screen. Maybe because of some netyissue or something, you might be encountering this issue. Are you running the RC instance locally?


Also you can take a look at this if you are getting this issue: https://github.com/RocketChat/EmbeddedChat/issues/368

**Comment by JeffreytheCoder** [comment]
@umangutkarsh Yes I'm running the RC instance locally. I keep encountering this issue on my end. Could you explain on the network issue you mentioned that causes this?
