### ISSUE TITLE
Add tooltips to message toolbox

### ISSUE THREAD

**Issue by JeffreytheCoder** [RocketChat/EmbeddedChat#486]
As an EmbeddedChat developer

**I need to**:
Add tooltips to message toolbox

**So That**:
It aligns with RC. We want many actions in the toolbox so having tooltips would help user identify the actions and understand what they do.

In RC:
<img width="1131" alt="Screenshot 2024-03-01 at 10 44 45 AM" src="https://github.com/RocketChat/EmbeddedChat/assets/35394596/a8b02e69-2ebe-4cd7-833a-7c37855fb73d">

Currently in EC:
<img width="1170" alt="Screenshot 2024-03-01 at 10 45 21 AM" src="https://github.com/RocketChat/EmbeddedChat/assets/35394596/656f5824-f200-496c-9f1b-e53f273ffc1d">

**Acceptance Criteria**
- [x] Show tooltips when hovering over actions on the message toolbox

**Comment by JeffreytheCoder** [comment]
Working on it

**Comment by maanvi21** [comment]
Hey, I would love to wok on this issue.. Could you please assign me this?
