### ISSUE TITLE
[BUG]: Link preview is not available.

### ISSUE THREAD

**Issue by Spiral-Memory** [RocketChat/EmbeddedChat#494]
### Description:

The link preview is not visible whenever a user sends a link; the preview should be visible.

### Steps to reproduce:

1. Set up the EmbeddedChat and Open Storybook.
2. Send a message along with a link.
3. Notice that only the link is available with no preview. However, in the Rocket Chat app, we do have the link preview option.

### Expected behavior:

The link preview must be visible and allow the user to click on it to open the link in a separate window.

### Actual behavior:

The link preview is not available.

https://github.com/RocketChat/EmbeddedChat/assets/78961432/4d988041-656e-47b9-963b-21789f894f9b

**Comment by umangutkarsh** [comment]
I think this issue was addressed earlier in #200 but not merged yet. 

Don't know the reason.

**Comment by Spiral-Memory** [comment]
> Hi, I think this issue was addressed earlier in #200 but not merged yet. 
> 
> Don't know the reason.

Oh, okay. I didn't notice that. Thank you for letting  me know about it. Anyway, it was raised by the maintainer himself, so let's wait for them to see and comment on the reason for the same. Waiting for their response.
