### ISSUE TITLE
Make search tab behavior consistent with threads & RC

### ISSUE THREAD

**Issue by JeffreytheCoder** [RocketChat/EmbeddedChat#496]
As an EmbeddedChat developer

**I need to**:
Make search tab behavior consistent with search behavior in the threads tab and the search tab in RC.

**So That**:
The new search tab...
1. Shows "no result" when search result is empty
2. Gives search results without clicking the search button. Instead, it fetches search results based on typed input with debouncing.
3. Displays messages in the same style as messages in the chat room (except without toolbox on hover)

**Current Behavior**
In the current search tab:
![search_before](https://github.com/RocketChat/EmbeddedChat/assets/35394596/acfe0cda-aa0b-40d6-883c-e352b6635c5e)

**Expected Behavior**
(I didn't press enter or press any button in the following recordings)

In threads tab:
![threads](https://github.com/RocketChat/EmbeddedChat/assets/35394596/59c5f99a-f958-4932-9ca0-5879e5ceeeb7)

In RC:
![search_rc](https://github.com/RocketChat/EmbeddedChat/assets/35394596/8a4216f4-42c3-4671-bfd0-9575def102d4)

**Acceptance Criteria**

- [x] Shows "no result" when search result is empty
- [x] Gives search results without clicking the search button. Instead, it fetches search results based on typed input with debouncing.
- [x] Displays messages in the same style as messages in the chat room (except without toolbox on hover)

**Comment by Spiral-Memory** [comment]
@JeffreytheCoder , Nice Observation but in your second issue, if you look at the original RC as well, it exhibits the same behavior. It doesn't require you to click on the search button but instead starts searching based on the typed input.
