### ISSUE TITLE
Change starred and pinned message windows to sidebar

### ISSUE THREAD

**Issue by JeffreytheCoder** [RocketChat/EmbeddedChat#498]
As an EmbeddedChat developer

**I need to**:
Change starred and pinned message windows to sidebar

**So That**:
They match with other options in the chat room (threads, search, mentions, members, and room information), which all show information in sidebars. RC also displays these options in sidebars. 

Currently, it's weird to have starred and pinned messages expand to full window while other options show as sidebar. Having this inconsistent UI could confuse users.

**Acceptance Criteria**

- [x] Change starred messages window to sidebar
- [x] Change pinned messages window to sidebar

**Comment by JeffreytheCoder** [comment]
Working on it...Since this is a design choice, welcome to share any opinion on this issue

**Comment by Spiral-Memory** [comment]
Currently, the sidebar is not a good choice, to be honest, for other purposes as well. It hides the space of the chat window rather than resizing the chat window and placing another window next to it with a border line, just as it is in the RC. So, it would be great if you could try addressing that first before focusing on this particular issue.

> Working on it. Welcome to share any opinions on this issue since it involves design choices

**Comment by JeffreytheCoder** [comment]
@Spiral-Memory Open a PR with the changes - feel free to try it out. I feel like the sidebars work better than the windows because they are consistent with the UI/UX flow of other options.

**Comment by JeffreytheCoder** [comment]
I think RC keeps these features as sidebars for a reason. Keeping the "special messages" in a separate place avoid confusing them with the normal flow of messages in the chat room.

You can see design in Slack and Discord also follow a popup window design.
<img width="1359" alt="Screenshot 2024-03-07 at 12 26 20 PM" src="https://github.com/RocketChat/EmbeddedChat/assets/35394596/eb488467-92a6-49b8-8660-e81a3e335cbf">
<img width="725" alt="Screenshot 2024-03-07 at 12 25 56 PM" src="https://github.com/RocketChat/EmbeddedChat/assets/35394596/416f3b0b-c31d-4dcb-8d6e-c004a3f283ec">

**Comment by Spiral-Memory** [comment]
> I think RC keeps these features as sidebars for a reason. Keeping the "special messages" in a separate place avoid confusing them with the normal flow of messages in the chat room.
> 
> You can see design in Slack and Discord also follow a popup window design.
> <img width="1359" alt="Screenshot 2024-03-07 at 12 26 20 PM" src="https://github.com/RocketChat/EmbeddedChat/assets/35394596/eb488467-92a6-49b8-8660-e81a3e335cbf">
> <img width="725" alt="Screenshot 2024-03-07 at 12 25 56 PM" src="https://github.com/RocketChat/EmbeddedChat/assets/35394596/416f3b0b-c31d-4dcb-8d6e-c004a3f283ec">

I understand, but it would be great if we follow a similar pattern in EC as well which is in RC —keeping two windows separate and not overlapping with each other.

**Comment by JeffreytheCoder** [comment]
Could you explain on this? I see all the current sidebars overlaying the chat window

**Comment by Spiral-Memory** [comment]
![Screenshot from 2024-03-08 22-23-45](https://github.com/RocketChat/EmbeddedChat/assets/78961432/caae2355-2ffa-4e3d-be15-fb5d1d8f6b0b)
![Screenshot from 2024-03-08 22-23-59](https://github.com/RocketChat/EmbeddedChat/assets/78961432/cbb04b65-9a7b-4ac5-8e4f-0cac3ea6fd55)

Look in RC. You can see that when you open the sidebar, the chat window shrinks, and both the chat window and sidebar are separated by a border.

While in EC, when you open the sidebar, it doesn't happen; rather, it is just above the chat window, hiding some of its parts.

![image](https://github.com/RocketChat/EmbeddedChat/assets/78961432/594822e1-c54d-4bc5-b46e-afa255d2d2e3)

**Comment by JeffreytheCoder** [comment]
Good point 👍 resizing the Window could be helpful. I noticed the sidebars all have individual components and I plan to do some refactoring...I could include this change while refactoring.

Regardless of this general issue, do you think keeping pinned and starred messages in sidebars is better?

**Comment by Spiral-Memory** [comment]
Yes, it is better to keep "pinned" and "starred" in sidebars, in my opinion if this issue is not there.

Sure, bro. While refactoring, please ensure that it remains an individual component even after that. What can be done is creating a general Sidebar component to encapsulate all the common code, and then other components can customize it. I was attempting this earlier, but doing it may introduce several bugs, so make sure you proceed with caution.

**Comment by JeffreytheCoder** [comment]
Created a new issue for the refactoring job: #504. @Spiral-Memory What were the issues you encountered when trying to do this?

**Comment by JeffreytheCoder** [comment]
@sidmohanty11 The PR #501 is good for review

**Comment by Spiral-Memory** [comment]
> @sidmohanty11 The PR #501 is good for review

It's already been reviewed by Siddharth, and he has also approved the changes. Just to let you know Abhinav is another maintainer of the EmbeddedChat project, and he has been asked by Siddharth to do the review too. Once done, if he will respond.

**Comment by Spiral-Memory** [comment]
> Created a new issue for the refactoring job: #504. @Spiral-Memory What were the issues you encountered when trying to do this?

Mmm... The major issue lies in extracting the common part and placing it into a shared sidebar component. However, various components have different variations, making it challenging to extract the common code. If you proceed, just be a little careful, as overlooking anything might lead to code breaks. As you move into this task, you'll sense it.

Additionally, there could be levels of modularization; for instance, the search box might be considered a separate component, or it could be part of the common sidebar. These architectural choices require careful consideration to ensure stability.
