### ISSUE TITLE
Blank appearance of the message list after filtering pinned or starred messages (when no message is pinned or starred)

### ISSUE THREAD

**Issue by Yashraj7890** [RocketChat/EmbeddedChat#499]
### Description:

If we go the pinned/starred messages section when no message has been pinned or starred then we have blank chat body, instead it would be better to have a simple message like in rocket.chat which would be more appropriate for the user.

![Screenshot (79)](https://github.com/RocketChat/EmbeddedChat/assets/98230836/4cac6216-c973-4118-85eb-269bf72e75db)

### Actual behavior:
![Screenshot (73)](https://github.com/RocketChat/EmbeddedChat/assets/98230836/d4c3703f-9ff3-46bf-a9f1-786427dcd369)

**Comment by JeffreytheCoder** [comment]
This change could be overrided by #498
