### ISSUE TITLE
Handle names as per RC core

### ISSUE THREAD

**Issue by sidmohanty11** [RocketChat/EmbeddedChat#50]
### Steps to reproduce:

1. Issue that occurred at the [demo page](https://sidmohanty11.github.io/embeddedchat-demo-deploy)

### Expected behavior:
Usernames should have been handled gracefully.

### Actual behavior:
It broke

**Comment by ayush3160** [comment]
Hi @sidmohanty11 , Can I work on this issue ?

**Comment by sidmohanty11** [comment]
Hey @ayush3160 definitely! 

See this line for reference,
https://github.com/RocketChat/EmbeddedChat/blob/9f094a9553cfb7c6eb9dcdb69db34bc876392c6e/src/lib/api.js#L83

We are just removing the spaces and putting periods there and after that lowercasing the entire string as the username. It is viable as of now, but check out how RocketChat core repo handles usernames/suggests username to the user and define that logic here.

**Comment by sidmohanty11** [comment]
@Shivam164 sure go ahead!

**Comment by ayush3160** [comment]
Hi @sidmohanty11 , actually I am working on this issue but I am confused on how we can verify if username already exists or not.
Right now rocket chat repo is using below logic for suggesting usernames.


  export function generateUsernameSuggestion(user: Pick<IUser, 'name' | 'emails' | 'services'>): string | undefined {

	let usernames = [];


	if (user.name) {
		usernames.push(name(user.name));

		const nameParts = user.name.split(' ');

		if (nameParts.length > 1) {
			const [first] = nameParts;
			const last = nameParts[nameParts.length - 1];
			usernames.push(name(first[0] + last));
			usernames.push(name(first + last[0]));
		}
	}

	if (user?.name) {
		usernames.push(name(user.name));
	}

	if (Array.isArray(user.services)) {
		const services = [
			...new Set(user.services.flatMap(({ name, username, firstName, lastName }) => [name, username, firstName, lastName])),
		];
		usernames.push(...services.map(name));
	}

	if (user.emails && user.emails.length > 0) {
		for (const email of user.emails) {
			if (email.address && email.verified === true) {
				usernames.push(slug(email.address.replace(/@.+$/, '')));
				usernames.push(slug(email.address.replace(/(.+)@(\w+).+/, '$1.$2')));
			}
		}
	}

	usernames = usernames.filter((e) => e);

	console.log('userName Array',usernames)

	for (const item of usernames) {
		if (usernameIsAvailable(item)) {
			return item;
		}
	}

	usernames.push(settings.get('Accounts_DefaultUsernamePrefixSuggestion'));

	console.log('userName Array',usernames)

	let index = Users.find({ username: new RegExp(`^${usernames[0]}-[0-9]+`) }).count();
	const username = '';
	while (!username) {
		if (usernameIsAvailable(`${usernames[0]}-${index}`)) {
			return `${usernames[0]}-${index}`;
		}
		index++;
	}
}

**Comment by sidmohanty11** [comment]
Hey @ayush3160 , I'm sorry I didn't know you were working on this or not. 

An issue that occurred in the demo page is that someone had a name in a foreign language so this logic broke (please check this also).

Yup, that is tricky. They are directly finding count of usernames from the model to check if it is taken or not. Can we have a modal to enter username for the first register(if username is not present)? And allow users to put username at that point? We could have the frontend error handling code there (username is taken or not).

@RonLek @Sing-Li @dnouv @debdutdeb any suggestions?

**Comment by ayush3160** [comment]
Hi @sidmohanty11 , I have solved the issue for the foreign name's by using another package called limax , it is being used by the RC core repo for handling foreign language name's. Let me know If I should raise a PR for that. 

Regarding to verification of username, we can get username's suggestion from making a get request to /api/v1/users.getUsernameSuggestion , So I think we can just make a get request to this route to get the username, when the username is not present, rather than handling it ourselves. Let me know if it sounds good, I'll start working on this then.

**Comment by sidmohanty11** [comment]
@ayush3160 Amazing! Go ahead. Thanks!

**Comment by debdutdeb** [comment]
Hi, can someone explain what the problem is exactly?

**Comment by sidmohanty11** [comment]
@debdutdeb sir, when a user with foreign name signs up the logic failed to create a username for them. As of now, the logic was naively - taking the name of user from google API call then doing this,
https://github.com/RocketChat/EmbeddedChat/blob/9f094a9553cfb7c6eb9dcdb69db34bc876392c6e/src/lib/api.js#L83

Also what if the username is taken, that would throw an error and similarly show a broken username(which is blank), that's why I was thinking how to approach this. One way would have been showing a modal + suggesting a username plus checking if it's already taken by calling the API. But I think it will be better directly to call the API (/api/v1/users.getUsernameSuggestion) and set that username. What do you think?

**Comment by sidmohanty11** [comment]
@ayush3160 do we need to install limax for foreign names or does getUsernameSuggestion API call will handle it for us?

**Comment by ayush3160** [comment]
@sidmohanty11 , It will handle it for us, no need to install limax.

**Comment by ayush3160** [comment]
Hi @sidmohanty11 , I have fixed the issue and have raised the PR. Please have a look and let me know if any changes are required.
