### ISSUE TITLE
Cannot login EmbeddedChat through username and password

### ISSUE THREAD

**Issue by thesynthax** [RocketChat/EmbeddedChat#507]
### Description:

I am not able to log into my server from the EmbeddedChat front-end. This happens on packages/react (storybook), packages/auth as well as using EmbeddedChat component in my React Website. The servers I tried on were the development server(6.7) and production stable server (6.6) both. I checked the host URL, went through the code, tried debugging yet no luck.
I went and did the HTTP request through "curl http://localhost:3000/api/v1/login -d 'username=blah&password=blah' " and it returned an OK response.

### Steps to reproduce:

In React Webapp or Storybook (yarn storybook in packages/react):
1. Click JOIN
2. Type in username and password
3. Click Login
4. Nothing happens

In auth frontend (yarn dev in packages/auth):
1. Type in username and password
2. Click Login
3. Error response appears

### Expected behavior:

Logging into my server

### Actual behavior:

Error response appears in case of auth frontend and nothing happens in case of react/storybook.

https://github.com/RocketChat/EmbeddedChat/assets/29705333/7d801aea-ad5b-456a-8909-28ec727103be

**Comment by Spiral-Memory** [comment]
Hey @thesynthax , Please try the follow the documentation properly while try to run this application. It is not a bug. 

Here is the documentation : https://github.com/RocketChat/EmbeddedChat/blob/develop/README.md

If you still find any issue, You can discuss it in support channel

**Comment by Spiral-Memory** [comment]
Hey @thesynthax  , Please try the follow the documentation while try to run this application. It is working properly in my system.

Here is the documentation : https://github.com/RocketChat/EmbeddedChat/blob/develop/README.md

If you still find any issue, You can discuss it in support channel or you discuss the same with me on LinkedIn : https://www.linkedin.com/in/zishanahmad72/

Do you have CORS enabled on your server ? If not please do enable it.. and even after that if it is not working, please share the console screenshot

**Comment by thesynthax** [comment]
Messaged on LinkedIn

**Comment by Spiral-Memory** [comment]
Yep replied. have a look

**Comment by thesynthax** [comment]
Solution: Enable CORS in the Administration settings of your Rocket.Chat server

**Comment by Spiral-Memory** [comment]
https://github.com/RocketChat/EmbeddedChat/wiki/FAQs
