### ISSUE TITLE
[Feature Request] Add a "Scroll to Top" button in EmbeddedChat

### ISSUE THREAD

**Issue by thesynthax** [RocketChat/EmbeddedChat#511]
As an EmbeddedChat/Rocket.Chat developer and user

**I need to**: Go to the first message at times

**So That**: I can check the start of the conversation in a room/channel.

**Acceptance Criteria**

- [ ] Add a "Scroll to Top" button to go to the first message as shown in the image below
![ss_138](https://github.com/RocketChat/EmbeddedChat/assets/29705333/446943b1-774b-4fe0-bf86-f8d17eb92448)

I am willing to submit a PR for this feature request.

**Comment by KhalanderCSE734** [comment]
I want to work on this issue. Can you please assign me this issue.
