### ISSUE TITLE
Add loading state to File upload modal

### ISSUE THREAD

**Issue by sidmohanty11** [RocketChat/EmbeddedChat#521]
![Screenshot 2024-03-17 at 5 38 08 PM](https://github.com/RocketChat/EmbeddedChat/assets/73601258/f4e5fc29-3bcc-4f34-80c2-7763c38f3c35)

**Comment by JeffreytheCoder** [comment]
Hey @sidmohanty11 could you describe this issue?

**Comment by sidmohanty11** [comment]
@JeffreytheCoder when we click "Send" it should show a loading spinner or Sending... with the button disabled

**Comment by JeffreytheCoder** [comment]
> @JeffreytheCoder when we click "Send" it should show a loading spinner or Sending... with the button disabled

gotcha! working on it

**Comment by ayush1108g** [comment]
@sidmohanty11 
i am getting this error how to fix it?
![image](https://github.com/RocketChat/EmbeddedChat/assets/105841420/d633a510-926c-40ad-a51d-7264ba474f18)

**Comment by Spiral-Memory** [comment]
> I am getting this error how to fix it? ![image](https://private-user-images.githubusercontent.com/105841420/313623655-d633a510-926c-40ad-a51d-7264ba474f18.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA3NTg1MDgsIm5iZiI6MTcxMDc1ODIwOCwicGF0aCI6Ii8xMDU4NDE0MjAvMzEzNjIzNjU1LWQ2MzNhNTEwLTkyNmMtNDBhZC1hNTFkLTcyNjRiYTQ3NGYxOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxOFQxMDM2NDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NDk4YTJjZDVmZjk3MDQzN2NlMzQwODA4NDgzNzkwZmE1NjI1OGRlZWMzNTBhMDY5ZjFlMWI3MDUzOTgwMDhjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.sPZQLvdghTLB01fXoxC7K841S7T9l5wbTdVzeBCflt0)

I think it's not the right place to ask, Please join https://open.rocket.chat/channel/embeddedchat and let's discuss there. 
Anyway, for you problem, after cloning the repo, in root directly run `yarn` and `yarn build`. It will fix the issue ig.

**Comment by thesynthax** [comment]
Hi @sidmohanty11, just added a PR fixing this issue. Please check out #524
