### ISSUE TITLE
[BUG] Menu doesn't close when multiple menus are open and the user clicks on another menu icon

### ISSUE THREAD

**Issue by Spiral-Memory** [RocketChat/EmbeddedChat#522]
### Description:

The menu opens and closes just fine if the user clicks outside the menu. However, if there are multiple menus on a page, the menu must close if the user clicks anywhere outside. Currently, it does close when you click outside the menu, but not when you click on another menu. It remains open.

### Steps to reproduce:

1. Set up embedded chat.
2. Upload at least 2 files in the chat.
3. Go to the file menu.
4. Observe the menu behavior as shown in the video.

### Expected behavior:

The menu must close when the user clicks anywhere except on the same menu.

### Actual behavior:

The menu does not close when the user clicks on another menu, and multiple menus remain visible.

https://github.com/RocketChat/EmbeddedChat/assets/78961432/ca54464d-8a3a-4953-8e8e-fb2f6b1241b0

Note: This issue is not specific to file-menu, but rather the menu component itself.

**Comment by Spiral-Memory** [comment]
Feel free to raise a PR fixing this issue.

Hint: In the Menu component (Menu.js), it only checks whether it has been clicked on something that is closest to `.ec-menu-wrapper`. If not, then close the menu. However, in the case of multiple menus, the `.ec-menu-wrapper` class is present in all.

![image](https://github.com/RocketChat/EmbeddedChat/assets/78961432/f3fa3aef-79e3-4fe7-81ff-3b6d7a7c3db0)

**Comment by Spiral-Memory** [comment]
@Akshun-01 You were looking for some issue to fix right? If you want, you can give it a try.

**Comment by Akshun-01** [comment]
Hey @Spiral-Memory, fixed the bug.
Would appreciate any changes or feedback.
