### ISSUE TITLE
[BUG] Starred & Pinned messages sidebars fetch APIs infinitely

### ISSUE THREAD

**Issue by JeffreytheCoder** [RocketChat/EmbeddedChat#531]
### Description:

Starred & Pinned messages sidebars fetch APIs infinitely, caused by a recent change in #525 

<img width="750" alt="Screenshot 2024-03-22 at 11 57 28 PM" src="https://github.com/RocketChat/EmbeddedChat/assets/35394596/4ec4cefd-c57f-4c2e-9287-058ba41405b5">

<img width="752" alt="Screenshot 2024-03-22 at 11 57 49 PM" src="https://github.com/RocketChat/EmbeddedChat/assets/35394596/6bf0e258-1540-430a-a2f9-7aede2462a75">

### Steps to reproduce:

1. Open starred or pinned message sidebar
2. See the infinite calls in the "Network" tab of the inspection tool

### Actual behavior:

![sidebar-rerender](https://github.com/RocketChat/EmbeddedChat/assets/35394596/d404830e-5297-4af3-a4c8-fc3ea55540c3)

### Expected behavior:

Only fetch API once when the sidebar is opened

**Comment by Spiral-Memory** [comment]
Yep @JeffreytheCoder I'm aware of it i checked last night... are you fixing it, or should I, do it?

**Comment by Spiral-Memory** [comment]
Maybe listening to Real-time Apis provided by RC for threads, pinned message and starred message? Will it be possible ? @JeffreytheCoder
