### ISSUE TITLE
[BUG] Image attachment can't expand or show original image

### ISSUE THREAD

**Issue by JeffreytheCoder** [RocketChat/EmbeddedChat#534]
### Description:

Image attachment can't expand or show original image

### Steps to reproduce:

1. Try clicking on any image attachment in message

### Expected behavior:

When clicking on a image attachment, shows the original image in full screen mode

**Comment by JeffreytheCoder** [comment]
Working on it

**Comment by Spiral-Memory** [comment]
Hey @JeffreytheCoder , I suggest you confirm with the maintainers once whether we need this or not. Like, consider this: the embedded chat has to be integrated into multiple other websites, as in chat app. In those contexts, space will be limited, so displaying the image fullscreen won't work properly. We need to maintain the aspect ratio and handle many cases. Therefore, once confirm with them before working on it.

**Comment by JeffreytheCoder** [comment]
@sidmohanty11 @abhinavkrin ^^

**Comment by sidmohanty11** [comment]
@JeffreytheCoder I think it will be a good addition! Let's use the [swiper](https://swiperjs.com/) and try to keep the UI/UX similar as the core RC - https://github.com/RocketChat/Rocket.Chat/blob/5b7623dfe45a450c7d18094617d176117ccc1e39/apps/meteor/package.json#L426C4-L426C10

**Comment by Spiral-Memory** [comment]
@sidmohanty11  
![image](https://github.com/RocketChat/EmbeddedChat/assets/78961432/543b3136-64c4-47c2-880f-766f57eb9ecc)

**Comment by sidmohanty11** [comment]
Thanks @Spiral-Memory!

**Comment by JeffreytheCoder** [comment]
I had no problem working with Swiper, but need a little help with fetching the original image.

In RC, if you check the source of the image attachment, it has `src` as the preview image link and `data-src` as the original image link.

```html
<img data-id="tmPWgDNGMWJh5wRZo" class="gallery-item" data-src="https://ucla.rocket.chat/file-upload/tmPWgDNGMWJh5wRZo/codeimage-snippet_22.png" src="https://ucla.rocket.chat/file-upload/JMrwvXTTSpdigDeW8/codeimage-snippet_22.png" width="360" height="122.25">
```

The Swiper in RC uses the data-id as the image url, as in [ImageGalleryProvider](https://github.com/RocketChat/Rocket.Chat/blob/c3fe00736370db6e54d88e930a4817d37493a709/apps/meteor/client/providers/ImageGalleryProvider.tsx#L20)

@sidmohanty11 @Spiral-Memory Any idea how we can get the original image link in EC? Right now all attachment urls, including the downloading link, only return the preview image

**Comment by Spiral-Memory** [comment]
Hey @JeffreytheCoder , nope, I don't have any idea regarding that. I'll check it tomorrow and respond back to you.

**Comment by JeffreytheCoder** [comment]
> Hey @JeffreytheCoder , nope, I don't have any idea regarding that. I'll check it tomorrow and respond back to you.
> 
> 
> 
> Edit : Did you find a way ? I haven't tried yet. Little busy writing proposals. 

Not yet, I'm writing proposal too

Will dig deeper later this week

**Comment by JeffreytheCoder** [comment]
@Spiral-Memory Found it! The original link is `attachment.title_link` while the preview link is `attachment.image_url`

**Comment by Spiral-Memory** [comment]
@JeffreytheCoder Awesome !

**Comment by JeffreytheCoder** [comment]
> @JeffreytheCoder Awesome !
> 
> Edit: I'm stuck with my final B.Tech presentation, honors, research paper publication, and lab exams. I thought I'd feel a little free after submitting the proposal, but then all of this happened.

@Spiral-Memory No worries lol 

Good luck with your presentation and exams!
