### ISSUE TITLE
[FEAT]: Add features related to Channel and user status

### ISSUE THREAD

**Issue by umangutkarsh** [RocketChat/EmbeddedChat#536]
As an EmbeddedChat developer

**I need to**: Add the following features

**So That**: The user experience can be improved.

**Features**

- [ ] **Feature of Leaving Channel** - This feature will will allow the users to leave the channel right from EC. 

- [ ] **Feature of Deleting the Channel** - This will allow the admin to delete a particular channel right from Embedded Chat.

- [ ] **Feature of Showing status of users** - This will allow users to show the current status of all the users of that channel.

- [ ] **Feature of Editing the Channel information** - This will allow users to edit the information about the channel right from EC.

*All of these will require researching the appropriate endpoints from the Rocket.Chat REST API and integrating them.*

![image](https://github.com/RocketChat/EmbeddedChat/assets/95426993/a54f8ba5-b51b-4aaf-9c98-86e1ec058b36)
Features related to channel^

![image](https://github.com/RocketChat/EmbeddedChat/assets/95426993/dd73773b-3112-43f6-94fe-8f498be0793a)
Features related to users^

**Comment by umangutkarsh** [comment]
Hey maintainers, Let me know if these would be useful, working on these. Wil make a PR shortly.
Thanks.

**Comment by umangutkarsh** [comment]
These are just draft PRs for my reference. No need to review. Will make final PRs after some changes.
Thanks.

**Comment by umangutkarsh** [comment]
@sidmohanty11 what do you think?
Please let me know.

**Comment by sidmohanty11** [comment]
I like the idea of showing user status, we can definitely add that. In my opinion, the other suggestions aren't necessary since Rocket.Chat already handles admin support well. We should focus our efforts on improving the UI/UX for users in EC where we can directly address "in-app chat" problems, rather than managing the entire Rocket.Chat platform.
