### ISSUE TITLE
[bug]: Issues with Read Only channel options

### ISSUE THREAD

**Issue by umangutkarsh** [RocketChat/EmbeddedChat#541]
### Description:
Currently the following are the issues of 'read-only' channel.
1. The read-only is not set dynamically to EC but is only set after page reload.
2. The read-only is also set for admins which should not be the case.
3. No appropriate message is displayed on EC when read-only option is toggled.

### Steps to reproduce:

1. Go to Rocket.Chat server
2. Set to channel to read-only and see the behaviour.

### Expected behavior:
The above mentioned issues should be resolved.

### Actual behavior:
[readonly.webm](https://github.com/RocketChat/EmbeddedChat/assets/95426993/b68ac887-3548-40f8-896d-5ac27a9af993)

**Comment by Spiral-Memory** [comment]
The issue mentioned in point 2 has was addressed before. Earlier, while fetching channelRoles, it used to return the general user role as well. Now, it only returns roles specific to the channel. Before making any changes, you just need to concatenate the general user role (which is saved in the userStore) with the channel specific role, and it will start working properly again." 

![image](https://github.com/RocketChat/EmbeddedChat/assets/78961432/d7c2507f-aa92-4854-b56e-ea6b609a2d0c)

**Comment by devanshkansagra** [comment]
Hey @umangutkarsh, I am currently working on this issue and I found another bug. that RCInstance.userInfo() does not working properly even if the user is logged in

![image](https://github.com/RocketChat/EmbeddedChat/assets/125076549/636df8b4-9167-4010-b8df-541319933d78)

output:

![image](https://github.com/RocketChat/EmbeddedChat/assets/125076549/d07b754c-cf0c-400b-b7f1-1490a632595a)

**Comment by devanshkansagra** [comment]
Hey I found an alternate way
```js
const userRes = await RCInstance.getAuth();
const isAdmin = userRes.currentUser.me.roles.includes('admin');
```
this works

**Comment by devanshkansagra** [comment]
By this I solved the second point i.e, The read-only is also set for admins which should not be the case.

**Comment by devanshkansagra** [comment]
Now working on remaining 2 points

**Comment by devanshkansagra** [comment]
Hey @umangutkarsh, on changing the room to readonly in Rocket chat, it gives a warning in EC, I think due to that it preventing the dynamic reload

Warning is
```
Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
    at ChatBody (http://localhost:6006/src_index_js.iframe.bundle.js:7190:3)
    at div
    at http://localhost:6006/vendors-node_modules_emotion_react_dist_emotion-react_browser_esm_js.iframe.bundle.js:1847:66
    at http://localhost:6006/src_components_Modal_index_js.iframe.bundle.js:158:3
    at http://localhost:6006/vendors-node_modules_emotion_react_dist_emotion-react_browser_esm_js.iframe.bundle.js:1847:66
    at div
    at http://localhost:6006/vendors-node_modules_emotion_react_dist_emotion-react_browser_esm_js.iframe.bundle.js:1847:66
    at http://localhost:6006/src_components_Modal_index_js.iframe.bundle.js:158:3
    at http://localhost:6006/vendors-node_modules_emotion_react_dist_emotion-react_browser_esm_js.iframe.bundle.js:1847:66
    at ChatLayout (http://localhost:6006/src_index_js.iframe.bundle.js:9251:71)
    at ToastBarProvider (http://localhost:6006/src_index_js.iframe.bundle.js:4362:3)
    at div
    at http://localhost:6006/vendors-node_modules_emotion_react_dist_emotion-react_browser_esm_js.iframe.bundle.js:1847:66
    at http://localhost:6006/src_components_Modal_index_js.iframe.bundle.js:158:3
    at http://localhost:6006/vendors-node_modules_emotion_react_dist_emotion-react_browser_esm_js.iframe.bundle.js:1847:66
    at ThemeProvider (http://localhost:6006/vendors-node_modules_emotion_react_dist_emotion-react_browser_esm_js.iframe.bundle.js:1886:64)
    at EmbeddedChat (http://localhost:6006/src_index_js.iframe.bundle.js:9868:3)
    at unboundStoryFn (http://localhost:6006/sb-preview/runtime.js:41:3330)
    at ErrorBoundary (http://localhost:6006/vendors-node_modules_storybook_addon-essentials_dist_actions_preview_mjs-node_modules_storybo-642a8b.iframe.bundle.js:1485:429) 
```

**Comment by devanshkansagra** [comment]
Could you please help me how to tackle this one?

**Comment by Spiral-Memory** [comment]
Hey @devanshkansagra 

There are many issues with state updates in the application.. it's very difficult to find the exact cause of this issue specifically. 

You try to debug it with console logs and figure out what might be causing it.. remove piece of code, understand it and try fixing it.

**Comment by devanshkansagra** [comment]
I have fixed the second point, just check it out

[Screencast from 2024-06-26 12-08-54.webm](https://github.com/RocketChat/EmbeddedChat/assets/125076549/6a9856f7-9036-4e6d-b878-af9a9772da3f)

**Comment by devanshkansagra** [comment]
> Hey @devanshkansagra
> 
> There are many issues with state updates in the application.. it's very difficult to find the exact cause of this issue specifically.
> 
> You try to debug it with console logs and figure out what might be causing it.. remove piece of code, understand it and try fixing it.
> 
> Also this issue has nothing to do with readonly channels.. in normal channels also, this warning is present

Hey @Spiral-Memory, could you please give an idea that how rocket.chat does this, so that I can get reference and I can debug easily

**Comment by Spiral-Memory** [comment]
Hey @devanshkansagra 

There are many issues with state updates in the application.. it's very difficult to find the exact cause of this issue specifically. 

You try to debug it with console logs and figure out what might be causing it.. remove piece of code, understand it and try fixing it. 

I'll suggest not doing it dynamically for now, there are many issues that need more attention than this.. however, it can be done, by studying the EmbeddedChat API, you will see a connect function there.. in that function we listen to realtime events. 

You can specify the event there, and trigger a callback function to achieve it

**Comment by devanshkansagra** [comment]
Ok so do I push the second point of the code?

**Comment by Spiral-Memory** [comment]
If you want to work on a good issue that I'm trying to fix for months.. let me know.. I'll tell you one

**Comment by devanshkansagra** [comment]
> If you want to work on a good issue that I'm trying to fix for months.. let me know.. I'll tell you one

Yeah sure I am very excited and interested

**Comment by devanshkansagra** [comment]
> Ok so do I push the second point of the issue?

.

**Comment by Spiral-Memory** [comment]
Yep, raise your PR, I'll review it once ! Thanks a lot for your contribution 😊

**Comment by Spiral-Memory** [comment]
> > If you want to work on a good issue that I'm trying to fix for months.. let me know.. I'll tell you one
> 
> Yeah sure I am very excited and interested

Great, let me raise that issue for you !

**Comment by devanshkansagra** [comment]
Yea ok

**Comment by devanshkansagra** [comment]
I also found one issue, not regarding this but the different one

**Comment by Spiral-Memory** [comment]
Sure, do let me know that issue !

**Comment by Spiral-Memory** [comment]
Let's connect on open.rocket.chat, create an account there, and let me know your username, I'll DM you.. let's discuss regarding this there !

**Comment by devanshkansagra** [comment]
Yea, sure

**Comment by devanshkansagra** [comment]
> > > If you want to work on a good issue that I'm trying to fix for months.. let me know.. I'll tell you one
> > 
> > 
> > Yeah sure I am very excited and interested
> 
> Great, let me raise that issue for you !

could you please do so that I can raise the PR

**Comment by Spiral-Memory** [comment]
> > > > If you want to work on a good issue that I'm trying to fix for months.. let me know.. I'll tell you one
> > > 
> > > 
> > > Yeah sure I am very excited and interested
> > 
> > Great, let me raise that issue for you !
> 
> could you please do so that I can raise the PR

Don't be in a hurry about raising PRs.. that issue will take you some time to understand. Give it enough time to understand the issue, and see why this problem happens and how to fix it. I'm raising it right now.. please wait a little !

**Comment by devanshkansagra** [comment]
Ok

**Comment by Spiral-Memory** [comment]
Raised that issue ! Check it out
