### ISSUE TITLE
Add Jump to Message Feature

### ISSUE THREAD

**Issue by Akshun-01** [RocketChat/EmbeddedChat#552]
As an EmbeddedChat developer

**I need to**
Add a `Jump to Message` feature for pinned, starred messages, to access it easily.
![image](https://github.com/RocketChat/EmbeddedChat/assets/93793691/b937a9f5-2e76-40b6-9882-164c8d95bbe5)

**So That**:
This would allow users to access the pinned and starred message easily. 

[Optional] Also add the feature to allow users to `unPin` and `unStar` the messages right from the pinned and starred message menu respectively.
**Acceptance Criteria**

- [ ] Add the new options on Hover
- [ ] Implement Jump to Message feature
- [ ] Add the Unpin and UnStar functionality

**Comment by Akshun-01** [comment]
Working on this! ^^

**Comment by Suvendu-UI** [comment]
can i contribute to this issue ?

**Comment by Barrylimarti** [comment]
Looks an important feature. Working on this.

**Comment by r3yc0n1c** [comment]
hey @Barrylimarti  are you working on this? If not, I'm willing to work on it.

**Comment by Spiral-Memory** [comment]
Closing this issue as barrylimarti fixed it
