### ISSUE TITLE
[BUG] UI inconsistencies in quoted messages

### ISSUE THREAD

**Issue by Spiral-Memory** [RocketChat/EmbeddedChat#563]
### Steps to reproduce:

1. Setup Embedded Chat
2. Quote a message and send it, compare it with RC (UI has to be fixed and match with RC)
3. Now Quote a quoted message and do it recursively, the UI in EC will fail to render properly. In RC, 3 recursive messages can be quoted and 2 recent ones will be displayed on screen without fail.
4. Try to quote a image / video attachment, no preview is available

### Expected behavior:

UI consistency while quoting messages
Even in case of recursive quoted messages, the UI should render correctly (Refer to RC)
In case of attachment messages quoted, the preview should display correctly (In video, i have shown w.r.t image, test it with multiple attachments and ensure that everything is rendering properly.
 
### Actual behavior:

UI inconsistencies are present and UI fails to render properly when recursive messages are quoted.

https://github.com/RocketChat/EmbeddedChat/assets/78961432/e837052c-3adb-4c2e-8b34-4091ef840e52

Note: I think the code is written in PinnedAttachment.js for rendering, make sure it must not break or change pinned message notification UI

Edit:  The same has to be handled in QuoteAttachment preview as well.

https://github.com/RocketChat/EmbeddedChat/assets/78961432/e947d566-5a9e-41f3-b123-cd4f519b3390

**Comment by Spiral-Memory** [comment]
Hey Contributors, This is a very good issue to work on. If anyone is looking for an issue, it would be great to work on this one. I will work on it if no one shows interest. Otherwise, feel free to raise a PR for it.

**Comment by Akshun-01** [comment]
Hey, thanks for this! Working on it 🚀

**Comment by Spiral-Memory** [comment]
Great !

**Comment by Akshun-01** [comment]
Hi, Just an update from my side!

I have implemented the features mentioned in the issue. Just waiting for the quote message PR to get merged. Then I will make final changes and make a PR.

- Recurrsive Quotes:
![image](https://github.com/RocketChat/EmbeddedChat/assets/93793691/4d5e61ec-8ac9-47db-95cf-1a7cdaa2f1a4)

- Quoting Attachments: 
- Image:
![image](https://github.com/RocketChat/EmbeddedChat/assets/93793691/5a7b257c-b936-45c9-b760-35204efb89c6)

- Video:
![image](https://github.com/RocketChat/EmbeddedChat/assets/93793691/e20deca9-44a5-440e-94c2-255bd0f8b3df)

- Audio:
![image](https://github.com/RocketChat/EmbeddedChat/assets/93793691/a628f947-e69a-4fac-8811-ebfb6c157682)


PS: I have not added the CSS for attachments as of now. It will be similar to what is with Text quoting. And, I would add it in the final PR.

Thankyou! ^^

**Comment by Spiral-Memory** [comment]
Looks awesome 😳😲
