### ISSUE TITLE
[FEAT]: Deploy monorepos

### ISSUE THREAD

**Issue by Spiral-Memory** [RocketChat/EmbeddedChat#612]
**As an EmbeddedChat developer:**

**We need to**:
Deploy the monorepos `docs`, `ui-elements`, `react`, and `layout-editor`.

**So that**:
Users can test them live.

**Acceptance Criteria**:
- [x] Deploy all mentioned monorepos on GitHub Pages. Since GitHub provides only a single URL per project (`https://rocketchat.github.io/embeddedchat`), we must use routes to display different pages such as `https://rocketchat.github.io/embeddedchat` for the `react` monorepo, `https://rocketchat.github.io/embeddedchat/layout-editor` for the `layout-editor`, and so on.

**References**:
- https://rocketchat.github.io/fuselage -> https://github.com/RocketChat/fuselage: This repo follows a similar structure for multiple monorepo deployments.
- https://www.thisdot.co/blog/deploying-multiple-apps-from-a-monorepo-to-github-pages: Provides a starting point on how to deploy.
- One of my PRs, https://github.com/RocketChat/EmbeddedChat/pull/586, can help understand how to deploy a Storybook.

Deployment can be tested on your own forked repo before raising the PR.

**Comment by Spiral-Memory** [comment]
This issue is open for everyone to work on. Feel free to raise a PR.

**Comment by smritidoneria** [comment]
Hey, I was trying to setup the deployment for docs , 

<img width="733" alt="Screenshot 2024-07-25 at 1 45 03 PM" src="https://github.com/user-attachments/assets/b6311f4d-709b-4d5c-8ded-b4372f682c17">

While the gh-pages branch is correctly populated with my documentation files, the GitHub Pages URL is not visible, and I cannot access the documentation through the expected URL.

Any help would be really appreciated

**Comment by Spiral-Memory** [comment]
Hey,

I suggest focusing on deploying both the `react` and `ui-elements` monorepo together first.

Regarding documentation and the layout editor, we will expand on these once my layout editor pull request is merged. After that, the documentation will be located in a `packages` directory.

For now, you should work on hosting both the `react` and `ui-elements` monorepos correctly on the same GitHub Pages site.

One potential issue with the documentation not displaying correctly might be due to incorrect build configuration or deployment.

GitHub Pages deploys either from a dedicated branch or a specified directory. For example, in my `deploy` pull request i mentioned in issue description, the path is set to `storybook-static`. Once the build process completes, an `index.html` file is generated in GitHub's temporary storage under the `storybook-static` directory, which is then used for display.

When dealing with multiple monorepos, ensure that GitHub builds each project and outputs everything into a single directory. For instance, the build should output to `build/index.html` for the `react` monorepo and `build/ui-elements/index.html` for the `ui-elements` monorepo, and so on.

**Comment by smritidoneria** [comment]
Okay, thanks
