### ISSUE TITLE
 Message Box Misalignment in Large Box Viewport

### ISSUE THREAD

**Issue by smritidoneria** [RocketChat/EmbeddedChat#616]
### Description:

When the viewport is set to a large box, the message box does not align properly and has unexpected space at the bottom. 

### Steps to reproduce:

1. Open the embedded chat.
2. Set the viewport to a large box.
3.Observe the message box.

### Expected behavior:

The message box should align properly without any unexpected space at the bottom.

### Actual behavior:

https://github.com/user-attachments/assets/38201537-5f97-4766-8c42-1216c2e2ce9f

**Comment by smritidoneria** [comment]
hey @Spiral-Memory ,This might be a bug in the default Storybook configuration.

**Comment by Spiral-Memory** [comment]
Currently, it's not very mobile-responsive, but it is no doubt a need! You can work on this and other mobile responsiveness issues. For example, the sidebar should cover the entire space in mobile mode. Feel free to address any other responsiveness issues you find.

**Comment by Spiral-Memory** [comment]
Hey @smritidoneria 

Are you working on resolving this ?

**Comment by smritidoneria** [comment]
No @Spiral-Memory , I'm currently tied up with another task and can't work on this

**Comment by abirc8010** [comment]
Hi , I have made a PR . Could you please review it?
