### ISSUE TITLE
[Feat] : Deploy PR Previews to GitHub Pages

### ISSUE THREAD

**Issue by devanshkansagra** [RocketChat/EmbeddedChat#617]
As an EmbeddedChat developer

**I need to**:
Deploy the preview of the changes made in a pull request to Github Pages

**So That**:
Maintainers and other users can get to see and review the output before it gets merged

**Acceptance Criteria**

- [ ] Deploy the changes made in pull request to Github pages

**Rough Example**
Make it something like this: `https://rocketchat.github.io/EmbeddedChat/pulls/pr-<pr-number>/`

**Comment by devanshkansagra** [comment]
Hey @sidmohanty11 and @Spiral-Memory, I am working on this !

**Comment by Spiral-Memory** [comment]
Sure @devanshkansagra

**Comment by devanshkansagra** [comment]
Hey @Spiral-Memory, which projects of monrepo do we have to add in this?

**Comment by Spiral-Memory** [comment]
For all (but for a start, you can test for Embedded Chat (as that's the most important one)

**Comment by devanshkansagra** [comment]
No I am talking about, do I add react, layout-editor, ui-elements?? or all??

**Comment by Spiral-Memory** [comment]
All (for testing, react is fine, but we need all)

**Comment by devanshkansagra** [comment]
ok
