### ISSUE TITLE
Starred Message in thread not visible in the Starred Message Model

### ISSUE THREAD

**Issue by smritidoneria** [RocketChat/EmbeddedChat#627]
### Description:

Starred message in thread is not visible in the Starred Message Model.

### Steps to reproduce:

1. Go to thread
2. Starred the Message
3. Open the starred message model from the top right view (from the dropdown)
4.  Starred message in the thread will not be visible in the model

### Expected behavior:

Starred message in thread should be visible in the Starred Message Model.

### Actual behavior:
https://github.com/user-attachments/assets/9f2c487d-fc4a-496f-bcfb-195007c56054

**Comment by Spiral-Memory** [comment]
Does this problem appear in pinning / searching messages as well ?

**Comment by smritidoneria** [comment]
@Spiral-Memory , Searching is working fine and in the thread, the user do not have any option to pin the message

**Comment by Spiral-Memory** [comment]
Is this behaviour consistent with Rocket.Chat ? 

We can't pin thread messages ?

**Comment by smritidoneria** [comment]
We can pin thread messages in Rocket.Chat

**Comment by Spiral-Memory** [comment]
Okay, so this is another issue we might need to fix. 

Okay thanks !

**Comment by smritidoneria** [comment]
Yes, I can work upon this to add feature of pinning the messages in the thread
