### ISSUE TITLE
Quoted messages overflow on long messages

### ISSUE THREAD

**Issue by abirc8010** [RocketChat/EmbeddedChat#658]
### Description:

When quoting long messages, the quoted message container overflows outside the visible area,

### Steps to reproduce:

1. Send a long message
2. Try quoting this message 
3. Observe that the quoted message content overflows outside the visible area.

### Expected behavior:

The quoted message container should wrap long text content without overflowing, ensuring the entire message is visible.

### Actual behavior:

[before_fix.webm](https://github.com/user-attachments/assets/6ac47204-3022-4dcd-8f20-a77dfb70659f)

**Comment by gaurav-132** [comment]
may i contribute in this bug?
