### ISSUE TITLE
Bug: Thread messages which are starred are not being showed up in the sidebar

### ISSUE THREAD

**Issue by Barrylimarti** [RocketChat/EmbeddedChat#668]
### Description:
If a message is in thread and it is starred, then it is not shown in the sidebar. It only appears when we open the thread not by default. This defeats the purpose of starred messages.
### Steps to reproduce:

1. Write a message in thread.
2. Star that message.
3. Get out of that thread, and check sidebar. It should not be visible there.

### Expected behavior:
Any message that is starred should be seen in the sidebar by default.

### Actual behavior:

https://github.com/user-attachments/assets/ee1d5fb1-0caf-4ac7-b87f-a7a78c6ff598

**Comment by mayankdhangar2408** [comment]
hey @Barrylimarti can u assign this issue to me

**Comment by Barrylimarti** [comment]
Hi @mayankdhangar2408 , no one assigns issues, you can directly work on them. Although, I have already raised a PR for this issue, you can check it out.

**Comment by mayankdhangar2408** [comment]
> Hi @mayankdhangar2408 , no one assigns issues, you can directly work on them. Although, I have already raised a PR for this issue, you can check it out.

okk sir
