### ISSUE TITLE
Each user should have only one reaction.

### ISSUE THREAD

**Issue by tazsq** [RocketChat/EmbeddedChat#670]
### Description:

When reacting on a message, currently a user can react with multiple emojis. But, a user should only have one reaction

### Steps to reproduce:

1. Hover on a message 
2. click on emoji tab & click on an emoji to react
3. repeat again step1,2 but this time pick different emoji

### Expected behavior:

I believe that each user should have only one reaction. If user clicks on other emoji :
->1. Remove current reaction.
->2. Add the new reaction.

**Comment by mayankdhangar2408** [comment]
hey @tazsq can u assign this issue to me and explain it in brief

**Comment by tazsq** [comment]
> hey @tazsq can u assign this issue to me and explain it in brief

Hey 👋 , no need to assign you can go ahead and work on this issue.

As I was explaining each user should only have 1 emoji reaction per msg, if user decides to change the emoji than the previous emoji selected by the user would not be active and new emoji would be added.

**Comment by mdfaizanahmed786** [comment]
Hey @mayankdhangar2408, are you still working on this issue? If no, can I go ahead and work on this? 
Looping @tazsq

**Comment by mayankdhangar2408** [comment]
> Hey @mayankdhangar2408, are you still working on this issue? If no, can I go ahead and work on this? Looping @tazsq

yes, currently I'm working on this issue

**Comment by mayankdhangar2408** [comment]
hey @tazsq can you provide me the link and documentation where i fork this issue

**Comment by tazsq** [comment]
> hey @tazsq can you provide me the link and documentation of the file in which changes will be made

Hey sorry, but I don't know the files.

**Comment by tazsq** [comment]
> > Hey @mayankdhangar2408 and @mdfaizanahmed786 I'm not able to setup the rocket chat server instance can you guys help? Can we connect in dm?
> 
> yes, for sure, i also had some questions

Here's my discord- tazimsq

**Comment by SinghaAnirban005** [comment]
@Spiral-Memory Could you confirm if this is a valid issue and not some sort of feature that Rocket Chat wants users to have .

**Comment by tazsq** [comment]
> @SinghaAnirban005
> 
> It's a feature.

Hey 👋 can you reopen and add the feature label if possible.
