### ISSUE TITLE
Mentions in Chat Messages Are Not Clickable and not displaying User Profiles

### ISSUE THREAD

**Issue by SinghaAnirban005** [RocketChat/EmbeddedChat#679]
### Description:

Mentions (@username) in the chat messages do not redirect or display their details when clicked. Instead, the mention appears as plain text without any interactive functionality.

### Steps to reproduce:

1. Go to the EmbeddedChat channel
2. Type a message containing a mention, e.g., @testuser, and send it.
3. Click on the mentioned username in the chat window.

### Expected behavior:
Clicking on a mentioned username (`@testuser`) should open a modal with the user's details.

https://github.com/user-attachments/assets/0d4b61f9-9bf5-44d6-80ce-1345715b728c

### Actual behavior:

The mention appears as plain text, and clicking on it does not trigger any action or provide user information.
Although it shows the user info on clicking the profile icon next to their message

https://github.com/user-attachments/assets/1a0eb136-1ddb-4380-8d81-e528add249ee

**Comment by SinghaAnirban005** [comment]
Am working on this issue !

**Comment by LakshayPuhal** [comment]
want to work on this issue.

**Comment by SinghaAnirban005** [comment]
@LakshayPuhal A PR has already been raised for this issue . Please solve issues that do not have a PR or find a new issue to work on.

**Comment by LakshayPuhal** [comment]
Sure

**Comment by LakshayPuhal** [comment]
sure.
Are you on of the mentors in rocket chat  for Gsoc??

**Comment by SinghaAnirban005** [comment]
No.
