### ISSUE TITLE
BUG: Sidepanel Width Expands Unexpectedly with Content

### ISSUE THREAD

**Issue by Spiral-Memory** [RocketChat/EmbeddedChat#685]
### Description:

In the Sidepanel, the width is initially fixed. However, once content is added to the Sidepanel, its width changes, which is not the desired behavior.  

### Expected Behavior:

The Sidepanel's width should remain fixed, and the content inside the panel should adjust to fit within the specified width.  

### Actual Behavior:  

https://github.com/user-attachments/assets/dbfbab64-b259-4121-a149-ba092a991631

**Comment by Spiral-Memory** [comment]
Feel free to work on this issue.

**Comment by r3yc0n1c** [comment]
roger that! WOI

**Comment by abirc8010** [comment]
Hey @Spiral-Memory @r3yc0n1c since I was already working on sidebar responsiveness , I have fixed this issue in my previous PR #634
