### ISSUE TITLE
Mentions in Chat messages do not display user profile on Click

### ISSUE THREAD

**Issue by SinghaAnirban005** [RocketChat/EmbeddedChat#689]
### Description:

Mentions (@username) in the chat messages do not redirect or display their details when clicked. Instead, the mention appears as plain text without any interactive functionality.

### Steps to reproduce:

1. Go to the EmbeddedChat channel
2. Type a message containing a mention, e.g., @testuser, and send it.
3. Click on the mentioned username in the chat window.

### Expected behavior:
Clicking on a mentioned username (`@testuser`) should open a modal with the user's details.

https://github.com/user-attachments/assets/0d4b61f9-9bf5-44d6-80ce-1345715b728c

### Actual behavior:

The mention appears as plain text, and clicking on it does not trigger any action or provide user information.
Although it shows the user info on clicking the profile icon next to their message

https://github.com/user-attachments/assets/1a0eb136-1ddb-4380-8d81-e528add249ee

**Comment by gaurav-132** [comment]
Can i work on this?

**Comment by SinghaAnirban005** [comment]
@gaurav-132 Once my PR is reviewed, feel free to jump in if there’s room for further improvements or additional suggestions. It might be best to wait for feedback on my PR before opening a new one to avoid duplicate efforts..  Till then you may explore other issues.
