### ISSUE TITLE
Edit Message Permissions Not Reflecting Properly in EmbeddedChat

### ISSUE THREAD

**Issue by SinghaAnirban005** [RocketChat/EmbeddedChat#701]
### Description:

In EmbeddedChat , changes to `edit message permissions` configured by the admin for a channel are not being reflected as expected. While users are still able to edit their own messages, they are unable to edit other user's messages even if the admin grants this permission to normal users. Also the admin itself is not able to edit other user's messages considering it has permissions to do the same.

### Steps to reproduce:

1. As an admin, go to the RC administration -> Permissions -> Edit Message
2. Grant the "edit message" permission to normal users.
3. Log in as a normal user and try to edit a message posted by another user in the EmbeddedChat.

### Expected behavior:

When admin grants user editing permission, user is able to edit other user's messages 

https://github.com/user-attachments/assets/15d16093-99a3-4e38-8c82-8a4b0d8ce14b

### Actual behavior:
When admin grants `user` editing permission, user is  not able to edit other user's messages 

https://github.com/user-attachments/assets/ab8ce5c3-869f-413c-b1b7-6d07c30e2e78

**Comment by devanshkansagra** [comment]
Hey @SinghaAnirban005, editing other users message isn't a security issue? I mean the modification of other's message can compromise integrity in communication. Idk why rocketchat has this? or may be the permission of editing message could be like this example suppose there is a main chat room of the company where there are all managers, stakeholders, team leaders, team members etc and in that only admins and other higher roles have rights for the modification of their message or pin a message and other activities. Like  you see in whatsapp that there is a feature of admins only where only admins have access to send and edit the message of their own.

**Comment by devanshkansagra** [comment]
and those who have edit access in our case we are users, so  if the permission is set to users we have rights to edit our own message

**Comment by SinghaAnirban005** [comment]
@devanshkansagra your approach definitely sounds better in terms of security but based on the implementation provided in Rocket Chat i went with the default flow . 
@Spiral-Memory could you provide your opinion on this

**Comment by devanshkansagra** [comment]
Yea @SinghaAnirban005, it's good that you are matching the flow of EmbeddedChat with RocketChat and this is the main goal of the EmbeddedChat, but bro you should think about the cases whether the fix or feat you implemented is causing any issue/security-breaches to the end users or not. now suppose you go with the default flow for example in this case of editing message of other users and if in future RocketChat has made some changes regarding this then it could be difficult and become more complex to solve.

**Comment by SinghaAnirban005** [comment]
Well @devanshkansagra it would entirely depend on the choices made by the Admin . Thus , keeping in mind the fact that rocket chat wont allow normal users to edit messages by default . Why don't we leave it upto Admins of channels to decide their fate. Having this fix wont harm

**Comment by SinghaAnirban005** [comment]
Yes, but lets be reasonable with the fact that there are roles other than just `user`  and there could be cases where Admin might need to leverage edit permissions to other groups such as moderators to edit slangs or abusive languages .
This fix would only ensure that Admins can at times leverage the edit permissions when necessary .
Also lets not assume the decisions of Rocket Chat .

**Comment by SinghaAnirban005** [comment]
Also to address your insecurities regarding this , if someday rocket chat makes changes . The fix i have made wouldn't break this application .  because all it does is fetches the permissions of editing . Thus lets say Rocket Chat makes a change to not allow any user to edit other's user's messages , then the fix i have made is flexible enough to adjust accordingly . No further changes would be necessary !!

**Comment by devanshkansagra** [comment]
It is still there RocketChat by default is not allowing any users to edit other user's message

**Comment by SinghaAnirban005** [comment]
It will allow the `Admin` to edit other's messages is what i want to convey !!
And if RC guys decide someday to not leverage this right to Admin too then my fix won't serve as an issue 
So for the time being i believe this change would ensure uniformity

**Comment by devanshkansagra** [comment]
Okay I agree for Admin and roles other than `user` it is fine to edit any  message for any absuive/bad communication. But for `user` role it should be prevented to edit other user's message what do you think about? Also I would request @Spiral-Memory to give his opinion also so that our never ending debate for a small thing can come to end :joy:

**Comment by SinghaAnirban005** [comment]
Yes, let admin of the channel decide that . I am not explicitly trying to give this feature to the normal users
