### ISSUE TITLE
FEAT: Forward message

### ISSUE THREAD

**Issue by r3yc0n1c** [RocketChat/EmbeddedChat#711]
As an EmbeddedChat developer

**I need to**:
Enable users to forward messages within the chat application.

**So That**:
Users can seamlessly share important messages or content with other recipients within the app.

**Acceptance Criteria**

- [ ] Messages can be selected and forwarded to individual users.
- [ ] Forwarded messages retain their original content, including text, attachments, or metadata.
- [ ] A "Forwarded" label or indicator is added to identify forwarded messages.

**Comment by r3yc0n1c** [comment]
I'm working on this, it'll also have a "Copy Link" option which depends on #709

**Comment by Spiral-Memory** [comment]
Hi @r3yc0n1c 
In EmbeddedChat, we mainly works with 1 channel, and not individual users or multiple channels, not sure how forwarded message will be used here, can you explain a bit

**Comment by r3yc0n1c** [comment]
we can't send/receive msgs from individuals?

**Comment by Spiral-Memory** [comment]
In EC, we can't

**Comment by r3yc0n1c** [comment]
oh okay, we can close this one then
