### ISSUE TITLE
Pinned Messages Not Displaying

### ISSUE THREAD

**Issue by imf-ali** [RocketChat/EmbeddedChat#78]
### Description:

When any user of a room pins a message, it is not displayed. Instead an icon is shown for indicating a pinned message.

### Steps to reproduce:

1. Pin any message
2. The pinned message should be displayed in a suitable format.
3. Pinned message should consist of who has pinned the message and which message has been pinned

### Expected behavior:

Message should get pinned and displayed in Embedded chat

### Actual behavior:

An icon is displayed instead.
<img width="373" alt="image" src="https://user-images.githubusercontent.com/42451210/211078649-3b117ed8-9f93-4d96-995c-977157773808.png">

**Comment by imf-ali** [comment]
Hey @sidmohanty11, can you assign this issue to me. I would like to work on this.

**Comment by sidmohanty11** [comment]
Yup we need this! Sure @imf-ali
