### ISSUE TITLE
Support to show which user is typing

### ISSUE THREAD

**Issue by ayush3160** [RocketChat/EmbeddedChat#85]
As an EmbedChat developer

**I need to**: Add a feature to show the username of the user that are typing.

**So That**: Embedded Chat users can see which user's are typing.

**Acceptance Criteria**

- [ ] Show the username's of user's that are typing like Rocket Chat shows.

![Screenshot 2023-01-14 055111](https://user-images.githubusercontent.com/89914602/212440733-93c8679c-51c0-4c5c-9b77-e8efc6892835.png)

**Comment by sidmohanty11** [comment]
🤩

**Comment by deepak7336** [comment]
can i work on this issue ?

**Comment by ayush3160** [comment]
Hi @deepak7336 , I am working on this issue. I will definitely let you know if I'll face any difficulties in solving this issue.
