### ISSUE TITLE
Support to show Sender Avatar 

### ISSUE THREAD

**Issue by VipinDevelops** [RocketChat/EmbeddedChat#88]
As an EmbedChat developer

**I need to**:  Add the avatar of the sender next to the message in the EmbedChat

**So That**: Users can easily identify who sent the message and improve the overall chat experience.

**Acceptance Criteria**

- [ ] The avatar of the sender is displayed next to the message in the chat
- [ ]  The avatar is pulled from the user's profile, if available
- [ ] The implementation does not impact the performance of the chat

**Expected behavior**
![image](https://user-images.githubusercontent.com/99081689/212610732-fb5bcb00-908f-4868-b40d-673c263ff247.png)

**Actual behavior**
![image](https://user-images.githubusercontent.com/99081689/212610774-b0fcba38-4350-4a74-9825-ebf5dd12efab.png)

**Comment by VipinDevelops** [comment]
Hello @sidmohanty11, I would like to work on the issue of adding the avatar of the sender next to the message in EmbedChat. Can you please assign this issue to me? Thank you!

**Comment by VipinDevelops** [comment]
Hey @sidmohanty11 I would like to work on this issue of adding the sender's avatar next to the message in EmbedChat, in order to enhance the user experience. I would greatly appreciate it if you assign this task to me. Thank you for your support and looking forward to your positive response.

**Comment by sidmohanty11** [comment]
Sure @VipinDevelops go ahead
