### ISSUE TITLE
Can't share images in embedded chat

### ISSUE THREAD

**Issue by r3yc0n1c** [RocketChat/EmbeddedChat#89]
### Description:

Shared images in embedded chat can't be opened. The uploaded files point to localhost.

### Steps to reproduce:

1. Upload a screenshot in the chat
2. Click on the link

### Expected behavior:

The image opens in a new tab

### Actual behavior:

![image](https://user-images.githubusercontent.com/57730879/212747759-31e8c919-da82-45ab-92f2-bec47dce94fd.png)

**Comment by r3yc0n1c** [comment]
Hi Team! I'd like to resolve this.
Thank you!

**Comment by sidmohanty11** [comment]
@r3yc0n1c Sure, go ahead!

**Comment by kanishkcs** [comment]
Hi , Team  I would like to work on this isssue , Can I?

**Comment by sidmohanty11** [comment]
Hey @kanishkcs this issue is similar to #96 for which there is an open PR here -> #99 . Feel free to take up any other issue. Thanks!
