### ISSUE TITLE
image not visible in chat on file upload

### ISSUE THREAD

**Issue by VenomFate-619** [RocketChat/EmbeddedChat#96]
### Description:
The image is not visible on the chat screen, it is visible as a link instead of an image.
The image uploaded from the Embedded chat is coming as a file.

### Steps to reproduce:

1. Click on + icon to add image 
2. Hit enter to send the image
3. The image would come as a file in the application
4. That image would also come as a file in the rocket chat server

### Expected behaviour:
![image](https://user-images.githubusercontent.com/67755128/213843851-082ed48e-dcd7-439c-b52f-9c2fa272fd8a.png)

### Actual behaviour:

![image](https://user-images.githubusercontent.com/67755128/213843863-f690f43c-3a9a-4a1e-a06d-297fbf46ac31.png)

**Comment by raghavpatidar** [comment]
Please give me this task; I'd like to work on it. This is my first issue on rocket.chat looks to be really intriguing, and I would really want to work on it.

**Comment by VenomFate-619** [comment]
Hey, @sidmohanty11 I have found this bug, I would like to work on this.

**Comment by VenomFate-619** [comment]
I think it happens because of the incorrect `content-type `sent to the server.

Actual one:-
![image](https://user-images.githubusercontent.com/67755128/213846552-959bcae1-96f8-438e-bb6c-0e528f592e34.png)


Expected One:-
![image](https://user-images.githubusercontent.com/67755128/213846599-58bbd973-2769-4ac6-94d0-f6d1dba7060a.png)

**Comment by sidmohanty11** [comment]
@VenomFate-619 @raghavpatidar anyone can work on it or surely you both can collaborate on this.

@VenomFate-619 Great research, I think we have to conditionally check for the file type and decide the content-type based on that - for example, for image -> `image/{{.ext}}`, `video/{{.ext}}` for pdf I think it can be octet-stream. Let me know what you think

**Comment by VenomFate-619** [comment]
@sidmohanty11 I would work on it.
I think the file Object itself has `type` in it.
So we can directly pass the file object in FormData , and formData will add type in `content-type`

`const fileObj = event.target.files && event.target.files[0];
console.log(fileObj.type);`

if do this we will get
![image](https://user-images.githubusercontent.com/67755128/213905404-5f2600aa-1161-4096-947b-0f7ca856a6f9.png)

**Comment by sidmohanty11** [comment]
@VenomFate-619 Awesome!
